wet-boew/GCWeb

src/footer/_screen-xxs-max.scss

Fixed the Canada wordmark being clipped in the xxsmall view

---

src/views/_print.scss

Enable the printing of glyphicons

---

src/priorities/_screen.scss
src/theme.scss

Priorities: Added SCSS file to fix issues related to overly-wide linked areas.

---

site/includes/promotion1.hbs
site/pages/institution-carousel-en.hbs
site/pages/institution-carousel-fr.hbs
site/pages/organizational-carousel-en.hbs
site/pages/organizational-carousel-fr.hbs
site/pages/theme-en.hbs
site/pages/theme-fr.hbs

Do not merge until this PR is merged upstream
https://github.com/wet-boew/wet-boew/pull/6458

DO NOT MERGE - made carousels fully clickable

---

site/pages/organizational-carousel-fr.hbs
site/pages/organizational-fr.hbs

changes to organizational profile French pages

---

site/pages/topic-lowest-en.hbs

Change to topic breadcrumbs

---

site/pages/ministerial-en.hbs
site/pages/ministerial-fr.hbs

changes to ministerial pages for release 1.5

---

site/pages/organizational-carousel-fr.hbs
site/pages/organizational-fr.hbs

updated organizational French pages

---

site/pages/institution-en.hbs
site/pages/institution-fr.hbs
site/pages/organizational-en.hbs
site/pages/organizational-fr.hbs

Fixed floating news issue in md screen

---

site/includes/footerresources.hbs

Fix https://github.com/wet-boew/wet-boew/issues/6658

Site: Link to jQuery using https

---

site/pages/theme-en.hbs
site/pages/theme-fr.hbs
site/pages/topic-en.hbs
site/pages/topic-fr.hbs

Moved the top tasks ahead in the reading order on theme and topics pages

---

site/includes/fullmenu-en.hbs
site/includes/fullmenu-fr.hbs

Adjusted taxes menu and replaced all ampersands "&" with "and".

updates to mega menu

---

src/_defaults.scss

CSS: Added a rule above the activities and initiatives block.

---

site/pages/servicecomplexe/index-en.hbs
site/pages/servicecomplexe/index-fr.hbs
site/pages/servicecomplexe/page2-en.hbs
site/pages/servicecomplexe/page2-fr.hbs
site/pages/servicecomplexe/page3-en.hbs
site/pages/servicecomplexe/page3-fr.hbs
site/pages/servicecomplexe/page4-en.hbs
site/pages/servicecomplexe/page4-fr.hbs
site/pages/servicecomplexe/page5-en.hbs
site/pages/servicecomplexe/page5-fr.hbs
site/pages/servicecomplexe/page6-en.hbs
site/pages/servicecomplexe/page6-fr.hbs

Service initiation page: new next/back buttons

---

src/tabs/_screen.scss

Tabs: Fix frontpage override specificity and override margin offset.

---

site/pages/ministerial-en.hbs
site/pages/ministerial-fr.hbs

added removed GA class from previous PR

added GA gc-nws class to section on ministers pages

---

Gruntfile.coffee
package.json

No failures have been fixed at this point. Some may be coming from upstream.
Closes #903

Build: Add bootlint to build

---

site/includes/promotion1.hbs

To be inline with PR wet-boew/wet-boew#6703

accessible carousel, remove title and added link text

---

site/pages/service-en.hbs
site/pages/service-fr.hbs

Ensures the simple service initiation page's right panel is consistent with the advanced pages.

Simple service initiation page: Added reference to right panel include.

---

site/includes/header.hbs
site/pages/content-signedoff-en.hbs
site/pages/content-signedoff-fr.hbs
site/pages/content-signedon-en.hbs
site/pages/content-signedon-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

Depends on wet-boew/wet-boew#7446

Added the sign on/off examples

---

site/pages/localnav/index-en.hbs
site/pages/localnav/index-fr.hbs
site/pages/theme-en.hbs
site/pages/theme-fr.hbs
site/pages/topic-en.hbs
site/pages/topic-fr.hbs

fixes #1063 
cc/ @EricDunsworth, @MRicher

replaced Ajax with pull

---

site/pages/service-en.hbs
site/pages/service-fr.hbs

changed breadcrumb for service page

---

site/includes/service-right-panel.hbs
site/pages/advancedservice/index-en.hbs
site/pages/advancedservice/index-fr.hbs
site/pages/advancedservice/page2-en.hbs
site/pages/advancedservice/page2-fr.hbs
site/pages/advancedservice/page3-en.hbs
site/pages/advancedservice/page3-fr.hbs
site/pages/advancedservice/page4-en.hbs
site/pages/advancedservice/page4-fr.hbs
site/pages/advancedservice/page5-en.hbs
site/pages/advancedservice/page5-fr.hbs
site/pages/advancedservice/page6-en.hbs
site/pages/advancedservice/page6-fr.hbs

changed the margin for the toc
changed ul to ol in toc

changes to advance service toc

---

src/_defaults.scss

added styles for iframe for Fluid Survey on Canada site

---

site/pages/service-en.hbs
site/pages/service-fr.hbs
src/template/_base.scss

Remove border from definition list on Service template

---

site/pages/service-fr.hbs

Fixed french translation in apply button on page

---

site/pages/service-en.hbs
site/pages/service-fr.hbs
src/template/_base.scss

@lucas-hay @MaximMartel Need to update tech spec

Moves contact class out of definition list and into a section element

---

src/secondary-menu/_base.scss

fix heading style for section nav to all non-links

---

site/pages/advancedservice/index-en.hbs
src/components/_base.scss
src/template/_base.scss

add the lnkbox to the boxes in the right column (PR #1169)
fix spacing for link boxes

modified the step by step navigation

---

src/social-media-icons/_base.scss

Fixes rendering issues in the [widgets demo page](http://wet-boew.github.io/themes-dist/GCWeb/widgets-en.html).

Social media icons: Restored left padding and center-vertical alignment in icon CSS.

---

site/includes/fullmenu-en.hbs
site/includes/fullmenu-fr.hbs

This should be merged in after #1178. Once that happens, this PR might run into merge conflicts. Should be super easy to resolve them if it comes to that.

Site: Changed mega menu HBS files to use i18n variables.

---

package.json

Revert "Tell travis to wait longer for updating the examples"

---

src/_defaults.scss
src/_variables.scss
src/news/_base.scss
src/views/_screen.scss

Related to wet-boew/wet-boew#7857 (but doesn't depend on it).

Theme: Added body/main background colour variables.

---

src/menu/_base.scss

linked to this PR https://github.com/wet-boew/wet-boew/pull/7944

adds padding to the .model-header class for the mobile panel

---

site/pages/topic-en.hbs
site/pages/topic-fr.hbs

Updated as per Content and IA Spec 3.2

Updated Topic page - removed alert banner and changed H1 title

---

site/pages/theme-en.hbs
site/pages/theme-fr.hbs

As per Content and IA Spec 3.2

Updated Theme page - removed alert banner and change h1 title

---

site/data/i18n/en.json
site/data/i18n/fr.json
site/includes/focuson.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs

Added section Focus on to homepage

---

site/pages/index-en.hbs
site/pages/index-fr.hbs

* Institutional profile for arm’s-length institutions
* 404 error page
* 404 error page (bilingual)

Index page: Added links to orphaned page templates.

---

Gruntfile.coffee

fix #1261 
Test: http://universallabs.org/wet/labs/gcweb-fix-1261/unmin/demos/data-json/template-en.html

Build - fix # 1261

---

src/_defaults.scss
src/template/_base.scss

Moved the RAP stuff from defaults.scss to /template/_base.scss as well 
My fix is live 208 to line 222

Added RAP CSS fix - Hide textarea and hide Other checkbox

---

src/plugins/actionmng/actionmng.js
src/plugins/data-json/data-json-doc-en.hbs
src/plugins/data-json/data-json-doc-fr.hbs
src/plugins/data-json/data-json.js
src/plugins/deps/template.js
src/plugins/doaction/doaction-doc-en.hbs
src/plugins/doaction/doaction-doc-fr.hbs
src/plugins/doaction/doaction.js
src/plugins/doaction/tblfilter-en.hbs
src/plugins/doaction/tblfilter-fr.hbs
src/plugins/jsonmanager/jsonmanager-doc-en.hbs
src/plugins/jsonmanager/jsonmanager-doc-fr.hbs
src/plugins/jsonmanager/jsonmanager.js
src/plugins/urlmapping/urlmapping-doc-en.hbs
src/plugins/urlmapping/urlmapping-doc-fr.hbs
src/plugins/urlmapping/urlmapping.js

For testing: http://universallabs.org/wet/labs/actionmng/unmin/demos/doaction/tblfilter-en.html
Working example & docs: 
* http://universallabs.org/wet/labs/actionmng/unmin/demos/doaction/tblfilter-en.html
* http://universallabs.org/wet/labs/actionmng/unmin/demos/doaction/tblfilter-fr.html
* http://universallabs.org/wet/labs/actionmng/unmin/demos/doaction/doaction-doc-en.html
*FYI - It need to rebase once #1272 are merged*
/cc @masterbee

Action manager plugin and Do action plugin - Initial commit

---

src/plugins/data-json/data-json-doc-en.hbs
src/plugins/data-json/data-json-doc-fr.hbs
src/plugins/data-json/data-json.js
src/plugins/deps/template.js
src/plugins/jsonmanager/jsonmanager-doc-en.hbs
src/plugins/jsonmanager/jsonmanager-doc-fr.hbs
src/plugins/jsonmanager/jsonmanager.js
src/plugins/urlmapping/urlmapping-doc-en.hbs
src/plugins/urlmapping/urlmapping-doc-fr.hbs
src/plugins/urlmapping/urlmapping.js

Also it fixes a little bug with the template polyfill
For testing: http://universallabs.org/wet/labs/gcwebml/unmin/demos/index-en.html
/cc @masterbee

Data-json and JSON manager - Added more filtering possibility

---

src/share/_screen-xs-max.scss
src/theme.scss

Share this page link: Use 100% width in extra small view and under.

---

site/includes/datemodified.hbs
site/includes/follow.hbs
site/pages/gc-audience-en.hbs
site/pages/gc-audience-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

added property attribute back to date modified
fixed follow us on gc audience page
updated two more templates to 1.4 on index page

fixed date modified and more spec 1.4 updates

---

site/includes/datemodified.hbs
src/_defaults.scss
src/share/_screen-xs-max.scss

* HTML:
* Improved Bootstrap grid layout implementation.
* Removed references to unnecessary SCSS classes (i.e. "datemod", "col-xs-12", "mrgn-tp-lg", "clearfix", "mrgn-tp-sm" and "pull-right").
* Changed grid widths in certain views to allow French content to fit on a single line at default text font size.
* Moved the "Report a problem on this page" details element into a parent div.
* Removed one of the "Share this page" link's parent divs.
* Removed the "Date modified" description list's parent div.
* Removed the "clearfix" div below the "Date modified" description list's parent div.
* Revised and simplified handlebars conditions.
* SCSS:
* Removed the "Date modified" description list's top margin. Its parent div already has a large top margin.
* Removed the "Report a problem on this …

Page details: Improved HTML/SCSS code.

---

src/plugins/data-json/data-json-doc-en.hbs
src/plugins/data-json/data-json-doc-fr.hbs
src/plugins/data-json/data-json.js
src/plugins/data-json/demo/data-en.json
src/plugins/data-json/demo/data-fr.json
src/plugins/data-json/template-en.hbs
src/plugins/data-json/template-fr.hbs

data-json: Added: Sub-template support, added support simple list of data and removed the requirement of pre-declaring attribute for template.
Working example:
* http://universallabs.org/wet/labs/data-json-oct-2017/unmin/demos/data-json/template-en.html

data-json: Added: Sub-template support and minor improvement

---

site/pages/institutional-service-performance-en.hbs
site/pages/institutional-service-performance-fr.hbs
src/plugins/fieldflow/advanced-en.hbs
src/plugins/fieldflow/advanced-fr.hbs
src/plugins/fieldflow/basic-en.hbs
src/plugins/fieldflow/basic-fr.hbs
src/plugins/fieldflow/fieldflow-en.hbs
src/plugins/fieldflow/fieldflow-fr.hbs

Related to wet-boew/wet-boew#8177.

Theme: Added nav/h2 elements to ToCs.

---

site/pages/gc-audience-en.hbs
site/pages/gc-audience-fr.hbs

replace clearfix with equal heights and cleaned up audience page

replace clearfix with equal heights and cleaned up audience page

---

site/includes/follow.hbs
site/pages/institution-arms-en.hbs
site/pages/institution-arms-fr.hbs
site/pages/institution-en.hbs
site/pages/institution-fr.hbs

@lucas-hay see the code change
Also, the handlebar conditional need to be a negative instruction, then you will be able to remove the "else".

Institutional template - Use proper grid when displaying Follow us content block

---

Gruntfile.coffee

Build - fix dependencies for data-JSON

---

Gruntfile.coffee
package-lock.json

Add the package-lock.json to avoid transient build failures.
Added the nested node_modules of wet-boew, because some of the modules seem to get nested as part of the install.

Fix Sass build issue

---

Gruntfile.coffee
package.json

The sub-resource integrity hash will be included with the release note.

Build - Added Sub-resource basic integrity generation

---

package-lock.json

Adds some missing grunt packages to the lock file

chore: Add missing lock file updates

---

src/plugins/urlmapping/urlmapping.js

It's because when a form is submited, space are encoded into "+" symbol instead of %20.
FYI - Real "+" symbol would be encoded into %2B

URL mapping - Convert "+" symbol in space

---

.editorconfig

Copy fix from https://github.com/wet-boew/wet-boew/pull/8446

chore: EditorConfig tabs -> tab

---

site/includes/breadcrumbs.hbs
site/includes/header.hbs
site/includes/languagetoggle.hbs
site/includes/sitemenu.hbs
src/breadcrumb/_base.scss

As per this PR
Test page available here:
* Home page:  http://universallabs.org/wet/labs/gcweb-v2+dev-0.5/unmin/home-en.html
* Page with a breadcrumb: http://universallabs.org/wet/labs/gcweb-v2+dev-0.5/unmin/organizational-en.html

V2 - Page header - Markup cleanup

---

Gruntfile.coffee
site/includes/sitemenu.hbs
site/pages/v2-menu-test-en.hbs
src/menu/_base.scss
src/plugins/menu/menu.js

There was some W3C validation issue with the preceding top menu markup. This new markup pass the W3C validation.
JS is incomplete and CSS need to be optimized.
Included a test page (v2-menu-test-en) to show the various state of the top menu

V2 - Top menu - Improved markup

---

site/includes/theme-topic.hbs
site/includes/topic-subtopic.hbs
site/layouts/default.hbs
site/pages/component/list-en.hbs
site/pages/component/list-fr.hbs
site/pages/content-en.hbs
site/pages/content-fr.hbs
site/pages/content-limit-en.hbs
site/pages/content-limit-fr.hbs
site/pages/gcweb/temp-v2issue.hbs
site/pages/gcweb/v2-migration.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs
site/pages/localnav/index-en.hbs
site/pages/localnav/index-fr.hbs
site/pages/theme-en.hbs
site/pages/theme-fr.hbs
site/pages/topic-en.hbs
site/pages/topic-fr.hbs
src/_defaults.scss
src/breadcrumb/_base.scss
src/campaign/_base.scss
src/promo/_base.scss
src/views/_screen-lg-min.scss
src/views/_screen-md-max.scss
src/views/_screen-md-min-to-screen-md-max.scss
src/views/_screen-sm-max.scss
src/views/_screen-xs-min-to-screen-xs-max.scss

The Review of the CSS class name was done during the last WET Technical review meeting.
The font size was adjusted based on requirement refined by TBS (related to internal issue 17, 18, 22, 24
added a placeholder for the gcweb new list styling.

V2  - Review of defined font-size and Review of CSS class name

---

.gitattributes

The src/fonts folder contains all of these file types.

.gitattributes: Added binary font file types.

---

site/includes/sitemenu.hbs
site/pages/gcweb/temp-v2issue.hbs
src/menu/_base.scss
src/plugins/menu/menu.js

Fix hover issue
Now conform with SC 1.4.13
Fixed an issue about SC 1.4.4.
Ensuring the menu separator orientation are properly adjusted for the keyboard nav with the most requested menu item.
Removed global initial set for the "tabindex" on each menu item.

V2 - Menu - Fix hover issue and now conform with SC 1.4.13

---

src/plugins/fieldflow/fieldflow-doc-en.hbs
src/plugins/fieldflow/fieldflow-doc-fr.hbs

fix wet-boew/wet-boew/issues/8515

Fieldflow - Docs - Clarified outputctnrid config

---

site/pages/ajax/sitemenu-v2-en.hbs
site/pages/ajax/sitemenu-v2-fr.hbs

Updated after discussions with IRCC

Update IRCC Help center label

---

.gitignore

update to gitignore

---

site/pages/home-en.hbs
site/pages/home-fr.hbs
src/_defaults.scss
src/views/_screen-sm-max.scss

- Fixed open gov links
- Doormats: paragraph fonts resized and line-height corrected
- Doormats: add mobile size specs for paragraph
- Change line-height of main copy

Fix doormat font size, body line-height and typo

---

site/pages/gcweb-theme/temp-v2issue.hbs
src/toc/_base.scss
src/views/_screen-xxs-max.scss

Also, the temporary list of open issues was reviewed and updated

V2 - multi-page navigation font fix + size fix for site search in xxs

---

site/pages/ajax/sitemenu-v2-en.hbs
site/pages/ajax/sitemenu-v2-fr.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs

Same as #1478 with conflict resolved and the markup for each services and information component used in the home page was updated.
close #1478 
/cc @patlaj

Some label and description edits [close #1478]

---

site/pages/gcweb-theme/temp-v2issue.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs
src/_defaults.scss

related to #1486 
and to the following issue in the temporary list
* Item 95
* Item 97

V2 - Limited width content, spacing in gc-srvinfo and spacing in home page

---

package-lock.json
package.json
site/pages/gcweb-theme/release/v5.0-en.hbs
site/pages/gcweb-theme/release/v5.0-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

Also move the release note location inside the gcweb-theme folder

Update build version to v5.1.0-development

---

site/includes/skiplinks.hbs

closes #1500
related wet-boew/wet-boew#8570

add nav element to skip navigation

---

site/pages/index-en.hbs
site/pages/index-fr.hbs

Also took out patterns that are no longer in the specs, and fixed a few other links.

Fixing links to specs

---

site/pages/gcweb-theme/temp-v5issue.hbs
src/plugins/menu/menu.js

Fix visual update temporary issue
* Item 73
* Item 74
Related
https://github.com/wet-boew/GCWeb/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature%3A+Menu+-+Plugin%22

Menu - Prevent menu closing for touch screen and basic instruction menu

---

site/pages/index-en.hbs
site/pages/index-fr.hbs
src/plugins/actionmng/actionmng.js
src/plugins/doaction/doaction-doc-en.hbs
src/plugins/doaction/doaction-doc-fr.hbs
src/plugins/urlmapping/geomap-en.hbs
src/plugins/urlmapping/geomap-fr.hbs
src/plugins/urlmapping/urlmapping-doc-en.hbs
src/plugins/urlmapping/urlmapping-doc-fr.hbs

This new feature is dependant on  https://github.com/wet-boew/wet-boew/pull/8611
Here a working example:
* http://universallabs.org/wet/labs/geomap-filter/demos/urlmapping/geomap-en.html
* http://universallabs.org/wet/labs/geomap-filter/demos/urlmapping/geomap-fr.html

Action manager - Add geomap filtering

---

site/includes/brand.hbs
site/layouts/default.hbs
site/layouts/servermessage.hbs
site/pages/gcweb-theme/index.hbs
site/pages/gcweb-theme/release/dev-build.hbs
site/pages/gcweb-theme/release/index.hbs

Include
- a RDFa fix for mainContentOfPage
- Little reorgarnisation of the release note to better documents the template changes

Structure Data - Set publisher to Government of Canada

---

src/buttons/_base.scss

Fixes a bug introduced by https://github.com/wet-boew/GCWeb/commit/6044d706d41a5fb9501e2ef9029f19945a493c34

Make primary buttons look the same everywhere on a page

---

site/pages/component/list-en.hbs
site/pages/component/list-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

Fixes some wet-boew-styleguide links.

Minor Link Fix

---

site/pages/video-en.hbs
site/pages/video-fr.hbs

**Note:** This will conflict with #1573 once that gets merged in.

Video example: Fix poster image links

---

src/plugins/actionmng/actionmng.js
src/plugins/doaction/doaction-doc-en.hbs
src/plugins/doaction/tblfilter-en.hbs
src/plugins/doaction/tblfilter-fr.hbs

action manager - Add table to CSV action

---

site/pages/ajax/sitemenu-v5-en.hbs
site/pages/ajax/sitemenu-v5-fr.hbs
site/pages/gcweb-theme/v5-migration.hbs

No menu items added nor removed.
Conflicts with PR #1575

Menu: Minor changes to the items (URLs and text)

---

site/pages/experimental-en.hbs
site/pages/experimental-fr.hbs
src/_experimental.scss
src/views/_screen-sm-min.scss

Depend on https://github.com/wet-boew/wet-boew/pull/8738 and to update to the latest wet-boew dependency.

Bootstrap 4 experimental CSS moved into stable WET-BOEW

---

src/plugins/fieldflow/fieldflow-doc-en.hbs
src/plugins/fieldflow/fieldflow-doc-fr.hbs

Thanks @fsnoddy for spotting this.

Fieldflow: Fix source code link in documentation

---

site/includes/sitemenu.hbs
site/pages/ajax/sitemenu-v5-en.hbs
site/pages/ajax/sitemenu-v5-fr.hbs

menu items replaced by cdn

---

.travis.yml
site/pages/component/gc-features-en.hbs
site/pages/component/gc-features-fr.hbs
site/pages/components-en.hbs
site/pages/components-fr.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

Fixes build required to bump WET-BOEW dependency to 4.0.33. 
Relates to #1628 
**(GC features now need documentation to track pattern updates over the history of GCWeb.)**

GC features pattern update and fixes build

---

site/pages/search/index.hbs
site/pages/search/results-contextual-en.hbs
site/pages/search/results-contextual-fr.hbs
site/pages/search/results-en.hbs
site/pages/search/results-filters-en.hbs
site/pages/search/results-filters-fr.hbs
site/pages/search/results-fr.hbs

advanced search added.
Related to #1632

advanced search added

---

package-lock.json
package.json
site/pages/gcweb-theme/release/v6.0-en.hbs
site/pages/gcweb-theme/release/v6.0-fr.hbs
site/pages/gcweb-theme/release/v6.1-en.hbs
site/pages/gcweb-theme/release/v6.1-fr.hbs

6.1 release note

---

site/pages/gcweb-theme/release/index-en.hbs
site/pages/gcweb-theme/release/index-fr.hbs
site/pages/gcweb-theme/release/v6.1-en.hbs
site/pages/gcweb-theme/release/v6.1-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

Minor fixes on release notes and its index.
Warning sign that the page won't be updated is added on changelog page.

Minor fixes on release notes and warning sign added

---

Gruntfile.coffee
site/includes/alert-provisional.hbs
site/includes/brand.hbs
site/pages/component/well-header-rwd-en.hbs
site/pages/gcweb-theme/release/dev-build.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs
site/pages/home/index.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs
site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs
site/pages/xprmntl/dark-theme-en.hbs
site/pages/xprmntl/dark-theme-fr.hbs
site/pages/xprmntl/pink-day-en.hbs
site/pages/xprmntl/pink-day-fr.hbs
src/_provisional.scss
src/plugins/bgimg/bgimg.js
src/plugins/fieldflow/fieldflow-doc-en.hbs
src/plugins/fieldflow/fieldflow-doc-fr.hbs
src/theme.scss

* "Moved to WET-BOEW" is added for bg-cover and bgimg.
* Changed experimental to provisional across all pages.

Experimental changed to Provisional

---

site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs
src/_provisional.scss

This is the design pattern that is for 'in case of crisis'

color for warning icon added

---

src/plugins/fieldflow/fieldflow-doc-en.hbs

Did a quick pass through. Mostly changes between subject-verb agreement.
close #1640 
\cc @RobJohnston

Correct spelling and grammar on English page

---

site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs
src/_provisional.scss

close #1650 
\cc @EricDunsworth

Provisional feature - Alert component redesign

---

package-lock.json
package.json
site/pages/gcweb-theme/release/v7.0-en.hbs
site/pages/gcweb-theme/release/v7.0-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs
site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs

Release note v7.0

---

site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs
src/plugins/chatwizard/_base.scss
src/plugins/chatwizard/chatwizard.js

Reset button and External button features are added.

chat wizard new features

---

site/pages/gcweb-theme/release/v7.0-en.hbs
site/pages/gcweb-theme/release/v7.0-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

Only fix content related issue in the gcweb web site

gcweb website - fix typos and broken links

---

site/layouts/splashpage.hbs
site/pages/splashpage.hbs

To replace current custom code

Splash page: Randomize background image with wb-randomize

---

package-lock.json
package.json
site/pages/gcweb-theme/release/v8.0-en.hbs
site/pages/gcweb-theme/release/v8.0-fr.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

Includes migration instructions for slim header. Release notes will be on GitHub.

Release v8.0

---

site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs
src/_provisional.scss
src/plugins/gc-subway/_base.scss
src/plugins/gc-subway/_screen-md-min.scss
src/plugins/gc-subway/gc-subway-en.hbs
src/plugins/gc-subway/gc-subway-fr.hbs
src/plugins/gc-subway/gc-subway.js
src/theme.scss

Provisional GC Service initiation template improvements from CRA, including:
- H1 red underline re-design
- Double H1 styling tied up with subway navigation menu

GC Subway map menu and short bold underlined H1 provisional features

---

site/pages/gcweb-theme/release/v8.0-en.hbs
site/pages/gcweb-theme/release/v8.0-fr.hbs

Waiting for WET-BOEW [PR #8893](https://github.com/wet-boew/wet-boew/pull/8893) to be merged and then GCWeb to bump its WET-BOEW dependency version.

Use of <ins> along with the <del> in code comparison

---

package-lock.json
package.json
site/pages/index-en.hbs
site/pages/index-fr.hbs

Release notes are now in the release section on GitHub only.

Release v8.0.1 documentation

---

package-lock.json
package.json
site/pages/index-en.hbs
site/pages/index-fr.hbs

This is a **PATCH release** (without breaking changes):
* **Styles and plugins:**
* Patch - Action Manager - Add BOM to UTF-8 file to fix character encoding on CSV export
* **[Provisional](https://wet-boew.github.io/themes-dist/GCWeb/provisional-en.html):**
* Edit - Chat wizard - Fix special characters in French invisible text
* Edit - GC Subway - Multiple small fixes (e.g.prevent blinking)
* Add - Checkbox & Radio - Offer larger checkboxes and radio-buttons
* GCWeb/js/theme.js
* GCWeb/js/theme.min.js
* GCWeb/css/theme.css
* GCWeb/css/theme.min.css
Compiles with: [WET-BOEW v4.0.38 STR](https://github.com/wet-boew/wet-boew/releases/tag/v4.0.38)
[List of commits](https://github.com/wet-boew/gcweb/commits/v8.0.2)
GCWeb/js/theme.min.js: `Coming soon...`
------------
Ceci est un **déploiement …

Release v8.0.2 documentation

---

src/views/_screen-lg-max.scss
src/views/_screen-lg-min-to-screen-lg-max.scss
src/views/_screen-lg-min.scss
src/views/_screen-md-max.scss
src/views/_screen-md-min-to-screen-md-max.scss
src/views/_screen-md-min.scss
src/views/_screen-sm-max.scss
src/views/_screen-sm-min-to-screen-sm-max.scss
src/views/_screen-sm-min.scss
src/views/_screen-xl-min.scss
src/views/_screen-xs-max.scss
src/views/_screen-xs-min-to-screen-xs-max.scss
src/views/_screen-xs-min.scss
src/views/_screen-xxs-max.scss

Added comments to describe in pixels the various breakpoints that are applied in each files

Updated `scss` files in `src/views` 

---

site/includes/brand.hbs
site/layouts/default.hbs
site/layouts/servermessage.hbs
site/layouts/splashpage.hbs
site/pages/gcweb-theme/static-header-footer/bootstrap-3.html
site/pages/gcweb-theme/static-header-footer/bootstrap-4.html
site/pages/splashpage.hbs

WET - 123 Add resource attributes to the base template (for wb-main, wb-webpage, wb-publisher)

Add resource attributes to the base template (for wb-main, wb-webpage, wb-publisher)

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Create CODE_OF_CONDUCT.m
Create CONTRIBUTING.md
Update README.md

Create community files

---

src/plugins/gc-subway/_base.scss
src/plugins/gc-subway/_screen-sm-max.scss
src/plugins/gc-subway/gc-subway-en.hbs
src/plugins/gc-subway/gc-subway-fr.hbs
src/plugins/gc-subway/index-en.hbs
src/plugins/gc-subway/index-fr.hbs
src/plugins/gc-subway/page2-en.hbs
src/plugins/gc-subway/page2-fr.hbs
src/theme.scss

Also:
- got rid of the `.noline` class as requested by DTO in WET-147.
- added proper active menu item styles and semantic.
**Will probably conflict with #1751**

GC Subway - Remove sub-items from the list in working example

---

src/_defaults.scss
src/_variables.scss
src/components/_base.scss

... and increase reusability.
As demonstrated in #1758 also.

Adding SASS variables to ease component development

---

src/plugins/fieldflow/_base.scss
src/plugins/fieldflow/basic-en.hbs
src/plugins/fieldflow/basic-fr.hbs
src/plugins/fieldflow/fieldflow-en.hbs
src/plugins/fieldflow/fieldflow-fr.hbs
src/plugins/fieldflow/fieldflow.js
src/theme.scss

Fieldflow - Inline style and use first item as default

---

src/plugins/gc-subway/gc-subway.js

To align header and pattern to rest of content on left side for main page pattern.
@delisma @GormFrank

Added p-0 class to implimented pattern

---

site/pages/component/gc-features-en.hbs
site/pages/component/gc-features-fr.hbs

This design pattern update is to support the beta theme/topic template, as proposed by #1758

gc-feature - Design pattern add - Cohabit

---

package-lock.json
package.json
site/pages/index-en.hbs
site/pages/index-fr.hbs
site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs

v9.1.0 release

---

site/includes/brand.hbs
src/banner/_screen-sm-max.scss
src/banner/_screen-xs-max.scss

Banner: Affect style on img instead of a + remove hyperlink from FIP on home page

---

site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs
src/plugins/gc-subway/gc-subway-en.hbs
src/plugins/gc-subway/gc-subway-fr.hbs
src/plugins/gc-subway/index-en.hbs
src/plugins/gc-subway/index-fr.hbs
src/plugins/gc-subway/page2-en.hbs
src/plugins/gc-subway/page2-fr.hbs

---
name: General
about: Update to better aligned the documentation with the guidance
title: 'docs: Update GC Subway map documentation'
labels: ''
assignees: '@duboip, @GormFrank'
---
This PR clarifies the documentation surrounding the GC Subway component to avoid confusion with its relation with the Service Initiation template

docs: Update GC Subway map documentation

---

site/pages/theme-topic-en.hbs
site/pages/theme-topic-fr.hbs

---
name: Theme and topic template
about: Alignment between technical documentation and guidance
title: 'style: Update theme-topic-[lang].hbs'
labels: ''
assignees: '@GormFrank'
---
This PR reduces the font size of the 'Most requested' title and hides the 'Service and information' title for this specific case to follow TBS guidance on this new template.
#1773

style: Update theme-topic-[lang].hbs

---

components/wb-actionmng/actionmng.js
components/wb-data-json/data-json.js
components/wb-fieldflow/fieldflow.js
components/wb-jsonmanager/jsonmanager.js

Fixing eslint issue that prevent the CD script to run.

Fix eslint issue

---

Gruntfile.coffee
_data/components.json
_data/sites.json
sites/breadcrumbs/breadcrumbs-en.html
sites/breadcrumbs/breadcrumbs-fr.html
sites/breadcrumbs/inc-breadcrumbs.html
sites/breadcrumbs/index.json-ld
sites/includes/i18n.liquid
sites/includes/settings.liquid
sites/includes/variable-core.liquid
sites/layouts/core.html

* Fix broken link with méli-mélo demos and service and information component
* Updated breadcrumbs include and added initial documentation
* Added language direction page properties

Fixing broken links, settings and breadcrumbs

---

templates/splash/layout-splashpage.html
templates/splash/splashpage.md

---
name: message.min.css link
about: This pull request template to replace any reference to old resources base path theme
title: 'Update stylesheet link in layout-splashpage.html'
labels: ''
assignees: '@duboisp, @GormFrank'
---
This pull request template to replace any reference to old resources base path theme "https://wet-boew.github.io/themes-dist/GCWeb/css" and "https://wet-boew.github.io/themes-dist/GCWeb/assets" left. Mainly in the splashpage.

Update stylesheet link in layout-splashpage.html

---

_data/components.json
components/wb-fieldflow/advanced-en.html
components/wb-fieldflow/advanced-fr.html
components/wb-fieldflow/alternative-en.html
components/wb-fieldflow/alternative-fr.html
components/wb-fieldflow/basic-en.html
components/wb-fieldflow/basic-fr.html
components/wb-fieldflow/fieldflow-doc-en.html
components/wb-fieldflow/fieldflow-doc-fr.html
components/wb-fieldflow/fieldflow-en.html
components/wb-fieldflow/fieldflow-fr.html
components/wb-fieldflow/index.json-ld
sites/_defaults.scss

Increases the font size of Field flow elements following visual update in 2019, by adding the `.gc-font-2019`.
(Relates to WET-180)

Field Flow: Increased font size alternative

---

templates/splash/layout-splashpage.html
templates/splash/splashpage.md

Update metadata on Canada.ca splash page according to WET-150

Splash page - Update metadata

---

méli-mélo/2021-05-steps/index.html
méli-mélo/2021-05-steps/steps.css

Méli-mélo 2021-05-steps

---

méli-mélo/2021-05-conjunction/and-or.css
méli-mélo/2021-05-conjunction/index-fr.html
méli-mélo/2021-05-conjunction/index.html

Added index page with all class types and multiple examples. Also included evergreen implementation plan and considerations.

Méli-mélo - 2021-5-conjunction

---

méli-mélo/th-canadaday/canada-day.html
méli-mélo/th-canadaday/meta.md
méli-mélo/th-canadaday/style.css

Ready for peer review and approval
Here a working example: https://nfrenette.github.io/GCWeb/m%C3%A9li-m%C3%A9lo/th-canadaday/canada-day.html

Canada Day 2021 red thematic

---

components/wb-fieldflow/alternative-en.html
components/wb-fieldflow/alternative-fr.html
components/wb-fieldflow/fieldflow-doc-en.html
components/wb-fieldflow/fieldflow-doc-fr.html
components/wb-fieldflow/fieldflow.js

Blocked by #1817 
Close #1582 #1586
Related to WET-182

Fieldflow: Implement large inputs (GC-Chckbxrdio)

---

components/gc-subway/gc-subway-en.html
components/gc-subway/gc-subway-fr.html
components/gc-subway/gc-subway.js
components/gc-subway/page2-en.html

Also fixed sub-pages working examples layouts.

GC Subway: Fix index page display issue on desktop

---

.github/ISSUE_TEMPLATE/bug-en.md

* "Behaviour" is the preferred spelling for that word in Canadian English and internationally.
* "Behavior" is the preferred American English spelling.
* Port of wet-boew/wet-boew#9121

Bug issue template: Fix "behavior" typo

---

index-en.md
index-fr.md
package-lock.json
package.json

Release 9.4.1

---

méli-mélo/méli-mélo-en.html
méli-mélo/méli-mélo-fr.html
thématique/gc-thématique-en.html
thématique/gc-thématique-fr.html

Made it easier to understand, translated some text and added links for references.
Méli-mélo: https://gormfrank.github.io/GCWeb/m%C3%A9li-m%C3%A9lo/m%C3%A9li-m%C3%A9lo-en.html
Thématiques: https://gormfrank.github.io/GCWeb/th%C3%A9matique/gc-th%C3%A9matique-en.html

Méli-mélo & GC Thématiques: Update documentation

---

sites/main-footer/inc-footer.html
templates/home/home-en.html
templates/home/home-fr.html

Related to: wet-190
Add option in order to hide the RAP button from the Home page template.

Home page template - hide RAP button

---

_data/components.json
components/gc-servinfo/index.json-ld
misc/views/_screen-sm-max.scss
sites/_defaults.scss

Related to: 
- wet-141
- PR: #1859

GC Initiatives - apply excat same font size as doormat link (Round 2)

---

components/gc-featured-link/_base.scss
components/gc-featured-link/gc-featured-link-en.html
components/gc-featured-link/gc-featured-link-fr.html
templates/institutional/institution-landing-en.html
templates/institutional/institution-landing-fr.html

Related to: wet189 and wet-185

GC Featured link - Fix custom background color and adjust design pattern 

---

templates/home/home-en.html
templates/home/home-fr.html

Related to: WET-189
Blocked by: #1858

Home page - Change to Featured link to apply new pattern

---

components/gc-features/_base.scss
components/gc-features/gc-features-en.html
components/gc-features/gc-features-fr.html
sites/theme.scss

Related: WET-183
Blocked by: #1866

Features - Apply well, move link title below the image and adjust one tile feature

---

_data/templates.json
components/_provisional.scss
templates/home/layout-home.html
templates/thematic/dark-theme-home-en.html
templates/thematic/dark-theme-home-fr.html
templates/thematic/index.json-ld
templates/thematic/pink-day-home-en.html
templates/thematic/pink-day-home-fr.html

Added missing working example of the home page for the provisional thematic pages.

Add working example - Thematic home page

---

components/json-fetch/json-fetch.js
components/wb-data-json/data-json.js

Correctif en lien avec les changements appliqué à jQuery via ce PR https://github.com/wet-boew/wet-boew/pull/9210

Coeur: Application des ajustements selon le correctif jQuery

---

index-en.md
index-fr.md
package-lock.json
package.json

GCWeb Release v10.0.0 (compiled with wet-boew v4.0.44)
TODO:

Release v10.0.0

---

index-en.md
index-fr.md
package-lock.json
package.json

This is to bump WET-BOEW dependency to include hot fix for v4.0.44.
**To do:**

Release v10.0.1 (STR)

---

_data/templates.json
templates/ministerial/index.json-ld
templates/ministerial/parliamentary-secretaries-reduced-en.html
templates/ministerial/parliamentary-secretaries-reduced-fr.html

Related to: WET-210
Addition of a new design pattern for reduced Parliamentary Secretaries profiles to the reduced Ministerial profile pages template.

Reduced Ministerial profiles - Addition of Parliamentary Secretaries

---

docs/developing-en.md
docs/developing-fr.md
index-en.md
index-fr.md

Total revamp of the index page to improve UI/UX on both Mobile and Desktop and make it look a little bit like the [WET-BOEW style guide](https://wet-boew.github.io/wet-boew-styleguide/index-en.html).

Revamp of the index page

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v10.3.0

---

_data/sites.json
_data/templates.json

This is content change in order to fix the glitch with the links related to the footer options in GCWeb the index page.

Footer options - fix broken links on index page

---

components/json-fetch/json-fetch.js
components/wb-actionmng/actionmng.js
components/wb-data-json/data-json-doc-en.html
components/wb-data-json/data-json-doc-fr.html
components/wb-data-json/data-json.js
components/wb-doaction/doaction-doc-en.html
components/wb-doaction/doaction-doc-fr.html
components/wb-jsonmanager/jsonmanager-doc-en.html
components/wb-jsonmanager/jsonmanager-doc-fr.html
components/wb-jsonmanager/jsonmanager.js

JSON-fetch - Fetch with custom data and post method

---

Gruntfile.coffee

adding release version and current date in theme.js file.

adding release version and current date in theme.js file

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v10.5.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v10.5.1

---

sites/theme.scss

Addition of the utility class for testing text spacing.
Related to release v10.5.1 -  #1935

Test utility - Text Spacing

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v10.5.2

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v10.5.3

---

components/wb-data-json/demo/data-en.json
components/wb-data-json/demo/data-fr.json
components/wb-data-json/template-en.html
components/wb-data-json/template-fr.html
sites/layouts/core.html

- Updating  data tables working example in data JSON.
- Fixing the page language selector in French by inserting the i18n variable in core.hml

Site maintenance - Update Data JSON Working Example and fix language

---

méli-mélo/th-canadaday/canada-day.html
méli-mélo/th-canadaday/meta.md
méli-mélo/th-canadaday/style.css

Updated red hex and added beige CSS and examples

Thematic update for Canada Day

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v10.5.5

---

sites/archived/archived-en.html
sites/archived/archived-fr.html
sites/archived/index.json-ld
sites/headers-includes/archive.html
sites/includes/i18n.liquid
sites/layouts/core.html

Fix includes, add i18nText and update variables.

Archived template - Updated working examples

---

sites/gcweb-menu/gcweb-menu-en.html
sites/gcweb-menu/gcweb-menu-fr.html
sites/header/deprecated/header-v1.html
sites/header/deprecated/home-v1.html
sites/header/header-en.html
sites/header/header-fr.html

Adjustement to the Header and GCWeb documentation with a before and after example.

GCWeb Menu and Header - Before and After

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v11.1.0

---

Dockerfile

Adding necessary update to Ruby system to be able to complete Docker container build.

Build: Fixing Docker container build

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v11.1.2

---

templates/search/api-en.html
templates/search/api-fr.html
templates/search/index.json-ld
templates/search/results-advanced-en.html
templates/search/results-advanced-fr.html
templates/search/results-contextual-en.html
templates/search/results-filters-en.html
templates/search/results-filters-fr.html
templates/search/results-fr.html

Search template: Personal information notification

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v11.2.0

---

components/list/list-en.html
components/list/list-fr.html
sites/baseline/lists/_lists.scss
sites/baseline/lists/_screen-lg-min.scss
sites/baseline/lists/_screen-md-min.scss
sites/baseline/lists/_screen-sm-min.scss
sites/theme.scss

Adding utility classes to be able to display lists in a column format distributed horizontally. Possibility to have 1, 2, 3 or 4 columns.

Lists: Adding flexbox list columns utility classes

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v11.3.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v11.3.1

---

méli-mélo/2021-05-conjunction/and-or.css

Fixing parent child relationship so child elements are directly relational only to the direct parent, thus could allow for nested and/or lists inside (for more complex explaination).  Will update example page with what that would look like when merged.

Creating direct parent/child dependencies

---

index-en.md
index-fr.md

Layout of Sites and global functionality changed to match Templates and Components layout.

Documentation: Changing index page global elements listing layout

---

_data/méli-mélo.json
index-en.md
index-fr.md
méli-mélo/2022-09-svgimagemap/meta.md
méli-mélo/compilation-gelé/2022-06-banff.css
méli-mélo/compilation-gelé/index.md
package-lock.json
package.json

Release v11.4.0

---

méli-mélo/2021-05-conjunction/index.html

added nested decision point example

2021-05-conjunction méli-mélo project - Update index.html

---

sites/authentication/authentication-en.html
sites/authentication/authentication-fr.html
sites/authentication/contextual-signin-en.html
sites/authentication/contextual-signin-fr.html
sites/authentication/contextual-signin-label-extended-en.html
sites/authentication/contextual-signin-label-extended-fr.html
sites/authentication/contextual-signin-nolabels-en.html
sites/authentication/contextual-signin-nolabels-fr.html
sites/authentication/contextual-signin-nomenu-en.html
sites/authentication/contextual-signin-nomenu-fr.html
sites/authentication/index.json-ld
sites/authentication/signedoff-en.html
sites/authentication/signedoff-fr.html
sites/authentication/signedon-en.html
sites/authentication/signedon-fr.html
sites/includes/i18n-core.liquid

Contextual Sign in button - Align Documentation with DTO

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v11.5.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v11.6.0

---

LICENSE

License - Crown copyright statement changes

---

_data/components.json
_data/sites.json
_data/templates.json
components/gc-subway/index.json-ld
package-lock.json

Make our main index page up to date with all our recent changes and changed the main example page for the subway navigation component for the index page and not the first sub-page

Site maintenance - Update indexes and subway main example link

---

index-en.md
index-fr.md
package-lock.json
package.json

Release 12.0.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release 12.1.0

---

méli-mélo/2021-05-steps/index.html
méli-mélo/2021-05-steps/meta.md
méli-mélo/2021-05-steps/steps.css

Complete re-structure of CSS code, slight redesign of circle pattern and introduction of potential alternative pattern.

Méli-mélo - 2021-05-steps - Update steps.css

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.2.0

---

components/gc-features/gc-features-doc-en.html
components/gc-features/gc-features-doc-fr.html
components/gc-features/gc-features-en.html
components/gc-features/gc-features-fr.html
components/gc-features/index.json-ld

- Add working example for each cohabit patterns variant.
- Separate documentation and working examples
- Adjust documentation to reflect these changes

Context-specific features - Add new patterns

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.2.1

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.3.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.4.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.5.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.5.1

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.5.2

---

sites/feedback/ajax/report-problem-en.html
sites/feedback/ajax/report-problem-fr.html
sites/feedback/ajax/report-problem-v2-en.html
sites/feedback/ajax/report-problem-v2-fr.html
sites/feedback/feedback-docs-en.html
sites/feedback/feedback-docs-fr.html

Removing some options in Report a problem plugin.
Changes related to WET-299

Report a problem: remove some text

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.6.0

---

sites/footers/deprecated/footers-v1-en.html
sites/footers/deprecated/footers-v1-fr.html
sites/footers/deprecated/footers-v2-en.html
sites/footers/deprecated/footers-v2-fr.html
sites/footers/deprecated/footers-v3-en.html
sites/footers/deprecated/footers-v3-fr.html
sites/header/deprecated/header-auth-v2.html
sites/header/deprecated/header-auth-v3.html
sites/header/deprecated/header-v1.html
sites/header/deprecated/header-v2.html
sites/header/deprecated/header-v3.html
sites/page-details/deprecated/page-details-v1-en.html
sites/page-details/deprecated/page-details-v1-fr.html
templates/home/deprecated/home-auth-v2.html
templates/home/deprecated/home-auth-v3.html
templates/home/deprecated/home-v1.html
templates/home/deprecated/home-v2.html
templates/home/deprecated/home-v3.html

Resolving build warnings part 1:
- Changing "layout: false" to "layout: null" as liquid does not support "false"

Build warnings: fixing no layout pages

---

components/gc-servinfo/_base.scss
sites/theme.scss

components/gc-servinfo/_base.scss was missing from theme.scss
Changes related to WET-305

gc-servinfo: Adding reference to base scss file

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.6.1

---

sites/feedback/includes/feedback.html

Test, when there is no site config or when the page feedback property are set to an empty string.

Theme: Feedback - Jekyll, No ajax when link are undefined

---

_data/components.json
components/gc-subway/_base.scss
components/gc-subway/_screen-md-min.scss
components/gc-subway/_screen-sm-max.scss
components/gc-subway/docs-en.html
components/gc-subway/docs-fr.html
components/gc-subway/fragments/docs-questions.html
components/gc-subway/gc-subway.js
components/gc-subway/index-en.html
components/gc-subway/index-fr.html
components/gc-subway/index.json-ld
components/gc-subway/section-end-en.html
components/gc-subway/section-end-fr.html
components/gc-subway/section-rel-info-en.html
components/gc-subway/section-rel-info-fr.html
components/gc-subway/section-subtitle-en.html
components/gc-subway/section-subtitle-fr.html
components/gc-subway/section1-en.html
components/gc-subway/section1-fr.html
components/gc-subway/section2-en.html
components/gc-subway/section2-fr.html
components/gc-subway/sub-section-en.html
components/gc-subway/sub-section-fr.html
components/gc-subway/sub-section-noline-en.html
components/gc-subway/sub-section-noline-fr.html

GC-Subway: Stabilizing GC-Subway pattern

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.8.1

---

templates/ministerial/ministerial-doc-en.html
templates/ministerial/ministerial-doc-fr.html

Ministerial Profile - Fixing minor typos

---

index-en.md

index page : fix typo in meaning of status

---

sites/header/header-docs-en.html
sites/header/header-docs-fr.html

header: Fix broken links in docs

---

package-lock.json
package.json

update wetboew dependencies

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.9

---

_data/templates.json
_includes/components/gc-features/features.html
_includes/components/gc-follow-us/gc-follow-us.html
components/gc-features/samples/features.html
components/gc-follow-us/samples/gc-follow-us.html
index-en.md
index-fr.md
templates/gc-audience-en.html
templates/gc-audience-fr.html
templates/institutional/institution-arms-en.html
templates/institutional/institution-arms-fr.html
templates/institutional/institution-en.html
templates/institutional/institution-fr.html
templates/news/index.json-ld
templates/news/news-doc-en.html
templates/news/news-doc-fr.html
templates/news/news-en.html
templates/news/news-fr.html
templates/organizational/organizational-arms-en.html
templates/organizational/organizational-arms-fr.html
templates/organizational/organizational-en.html
templates/organizational/organizational-fr.html
templates/topic/topic-testcase-1-en.html
templates/topic/topic-testcase-1-fr.html

Resolving build warnings part 8:
- Adding gc-features sample file
- Fixing news templates

Build warnings: dept features, news

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.10.0

---

sites/footers/deprecated/footers-v4-en.html
sites/footers/deprecated/footers-v4-fr.html
sites/footers/footers-en.html
sites/footers/footers-fr.html
sites/footers/includes/footer.html
sites/footers/old-footers-en.html
sites/footers/old-footers-fr.html

Changing "All Contacts" to "All contacts" in English version of the global footer.
This triggers a major version of the global footer which moves from 4.0 to 5.0.
Changes related to WET-330

Footer: All Contacts to All contacts

---

components/wb-chtwzrd/docs.html

Taken from a pulse check with previous implementers of the chat wizard.

Chat wizard: Update doc to reflect plugin purpose

---

components/gc-subway/_screen-md-min.scss

GC-Subway: fix broken format RAP

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.11.0

---

sites/feedback/ajax/report-problem-en.html
sites/feedback/ajax/report-problem-fr.html
sites/feedback/ajax/report-problem-v3-en.html
sites/feedback/ajax/report-problem-v3-fr.html
sites/feedback/feedback-aa-en.html
sites/feedback/feedback-aa-fr.html
sites/feedback/feedback-docs-en.html
sites/feedback/feedback-docs-fr.html
sites/feedback/feedback-en.html
sites/feedback/feedback-fr.html
sites/page-details/includes/footer.html
sites/page-details/page-details-docs-en.html
sites/page-details/page-details-docs-fr.html

- Feedback: Adding JSON Manager Extractor and Data-JSON to RAP to generate hidden inputs automatically.
- Page details: switching `<footer>` to `<section>` element.
Changes related to WET-249.

Feedback: Adding JSON Manager to RAP

---

_data/sites.json
sites/breadcrumbs/_breadcrumb.scss
sites/breadcrumbs/breadcrumbs-en.html
sites/breadcrumbs/breadcrumbs-fr.html
sites/breadcrumbs/index.json-ld

Breadcrumbs: switching from > to glyhpicon

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.12.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v12.13.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v13.0.0

---

_data/méli-mélo.json
index-en.md
index-fr.md
package-lock.json
package.json

Release v13.0.1

---

méli-mélo/th-canadaday/canada-day.html
méli-mélo/th-canadaday/meta.md
méli-mélo/th-canadaday/style.css

Added feature card css and HTML example
Made improvements recommended in previous PR **https://github.com/wet-boew/GCWeb/pull/2156**

Added feature card and made recommended improvements

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v13.3.0

---

Gruntfile.coffee
docs/layouts/acr_wrote_en-en.html
docs/layouts/acr_wrote_en-fr.html
docs/layouts/assessment_wrote_en-en.html
docs/layouts/assessment_wrote_en-fr.html

Template to let us publishing ACR and assessments according to the ACR methodology here: https://github.com/wet-boew/wet-boew/pull/9580

Other - ACR methodology baseline template files

---

Gruntfile.coffee

- Adding the ability to define CSS feature detection files
- Adding ":has(*)" selector support detection (to be removed once Firefox fully supports ":has(*)" for at least 2 versions)
Dependent on https://github.com/wet-boew/wet-boew/pull/9595 being released.

Supports: Adding CSS feature support detection architecture

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v13.4.0

---

common/colour/colour-en.html
common/colour/colour-fr.html
common/colour/index.json-ld

This pull request includes a test page with working examples filled with lorem ipsum text for Utilities/helpers. More info can be found by referencing WET-319.

WCAG upgrade - Create test page for: Color (foreground/background) (Revised)

---

common/list/lists-en.html
common/list/lists-fr.html

Adding GCWeb example for newly added `.dl-inline` utility class.

Utility: dl-inline

---

_data/common.json
index-en.md
index-fr.md
package-lock.json
package.json

Release v13.5.0

---

sites/theme.scss

Adding missing Paginate plugin CSS from WET to GCWeb.

Paginate: porting paginate CSS to GCWeb

---

_data/components.json
components/labels/index.json-ld
components/labels/labels-en.html
components/labels/labels-fr.html

Addition of working examples of the "Label" component from the WET style guide: https://wet-boew.github.io/wet-boew-styleguide/design/labels-en

Labels - Addition of working examples from WET style guide

---

_data/components.json
index-en.md
index-fr.md
package-lock.json
package.json

Release v13.7.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v13.7.2

---

méli-mélo/2023-09-menu/about.html
méli-mélo/2023-09-menu/calendar.html
méli-mélo/2023-09-menu/campaign-menu.css
méli-mélo/2023-09-menu/campaign-menu.js
méli-mélo/2023-09-menu/index.html

Prototype menu for sandbox testing only. We will not use it for pages published to production.

Meli melo 2023 09 menu

---

_data/méli-mélo.json
index-en.md
index-fr.md
package-lock.json
package.json

Release v13.9.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v13.9.1

---

_data/méli-mélo.json
index-en.md
index-fr.md
package-lock.json
package.json

Release v13.10.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v13.10.1

---

_data/sites.json
sites/feedback/feedback-docs-en.html
sites/feedback/feedback-docs-fr.html
sites/feedback/index.json-ld
sites/layouts/documentation.html
sites/page-details/index.json-ld
sites/page-details/page-details-docs-en.html
sites/page-details/page-details-docs-fr.html

- Deprecating RAP
- Deprecating Page details 1.1 and 2.0
- Updating code samples with correct characters

Feedback: deprecating RAP and Page details 2.0

---

sites/header/header-docs-en.html
sites/header/header-docs-fr.html

Fixing small typo in GCWeb Menu documentation where the sitemenu ajax file was updated to v3 when it should have remained v2.

GCWeb Menu: fixing doc typo

---

index-en.md
index-fr.md
package-lock.json
package.json
sites/theme.scss

Release v14.0.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.1.0

---

package-lock.json

Related to wet-boew/wet-boew#9700.

Build: Update WET DataTables dependency to ~1.13.8

---

méli-mélo/th-canadaday/canada-day.html
méli-mélo/th-canadaday/meta.md
méli-mélo/th-canadaday/style.css

Added 3 new variations of tiles with one additional CSS class.

Canada Day thématique - Feature tiles update

---

méli-mélo/2021-05-conjunction/and-or.css

Made to be optimal for text zoom at 200%, removed padding issues that introduced horizontal scroll in tabs/expand hides, and reduced margins for each column to increase amount of text that can fit on a line.

Méli-mélo - 2021-05-conjunction - Update and-or.css

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.2.1

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.3.0

---

_data/components.json
_data/sites.json
components/gc-featured-link/index.json-ld
docs/layouts/acr_wrote_en-en.html
docs/layouts/acr_wrote_en-fr.html
sites/feedback/index.json-ld
sites/feedback/reports/acr-2023-autumn-en.html
sites/feedback/reports/acr-2023-autumn-fr.html
sites/feedback/reports/acr-2023-autumn.json

ACR = Accessibility Conformance Report
This PR also include reference to accessibility assessment for feature-link and feedback.

Feedback (PFT) - ACR report - Autumn 2023

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.4.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.5.0

---

common/scaffolding/index.json-ld
common/scaffolding/reports/ally-assess-1-en.html
common/scaffolding/reports/ally-assess-1-fr.html
common/scaffolding/reports/ally-assess-1.json
common/scaffolding/text-level-semantics.html
common/scaffolding/texte-niveau-semantique.html

---
closes #2189 #2125 #2130 #2128

Add working example for text level semantic in the scaffolding group

---

components/images/images-en.html
components/images/images-fr.html
components/images/index.json-ld

Addition of working examples of the Images component form the WET-BOEW Style Guide
---
close #2323

Images - add working examples from WET-BOEW style guide

---

_data/méli-mélo.json
index-en.md
index-fr.md
méli-mélo/compilation-gelé/2023-10-mount-revelstoke.css
méli-mélo/compilation-gelé/2023-10-mount-revelstoke.js
package-lock.json
package.json

Release v14.6.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.7.0

---

common/scaffolding/index.json-ld
common/scaffolding/reports/a11y-2-en.html
common/scaffolding/reports/a11y-2-fr.html
common/scaffolding/reports/a11y-2.json
common/scaffolding/reports/a11y-3-en.html
common/scaffolding/reports/a11y-3-fr.html
common/scaffolding/reports/a11y-3.json

Forms: WGAG 2.1 AA Assessment

---

components/gc-table/index.json-ld
components/gc-table/reports/a11y-6-en.html
components/gc-table/reports/a11y-6-fr.html
components/gc-table/reports/a11y-6.json
components/gc-table/reports/a11y-7-en.html
components/gc-table/reports/a11y-7-fr.html
components/gc-table/reports/a11y-7.json

GC Tables: WGAG 2.1 AA Assessment

---

components/labels/index.json-ld
components/labels/reports/a11y-8-en.html
components/labels/reports/a11y-8-fr.html
components/labels/reports/a11y-8.json
components/labels/reports/a11y-9-en.html
components/labels/reports/a11y-9-fr.html
components/labels/reports/a11y-9.json

GC Labels: WCAG 2.1 AA Assessment

---

sites/header/index.json-ld
sites/header/reports/a11y-7-en.html
sites/header/reports/a11y-7-fr.html
sites/header/reports/a11y-7.json
sites/header/reports/a11y-8-en.html
sites/header/reports/a11y-8-fr.html
sites/header/reports/a11y-8.json

GC Header brand logo: WCAG 2.1 AA Assessment

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.8.0

---

_data/components.json
components/gc-most-requested/_base.scss
components/gc-most-requested/gc-most-requested-provisional-en.html
components/gc-most-requested/index.json-ld

Adding working example for the component in its provisional state prior to GCWeb v14.8.

Most requested: adding working example for provisional example

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.8.1

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v14.9.0

---

components/gc-subway/_screen-md-min.scss

GC-Subway: fix to support no javascript

---

_data/wet-boew.json
wet-boew/tagfilter/index.json-ld
wet-boew/tagfilter/reports/a11y-1-en.html
wet-boew/tagfilter/reports/a11y-1-fr.html
wet-boew/tagfilter/reports/a11y-1.json

Tagfilter: adding demo/doc links and partial a11y report

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.1.0

---

Gruntfile.coffee
_data/wet-boew.json

This PR is only about:
Build - Add grunt debug build task with no dependencies check
Content- Update our indexes files for the GCWEb website

Build - Add grunt build task with no dependencies check

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.2.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.2.2

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.3.0

---

index-en.md
index-fr.md
méli-mélo/2024-04-stepsquiz/meta.md
package-lock.json
package.json

Release v15.4.0

---

_data/components.json
_data/wet-boew.json
_includes/components/gc-contributors/gc-contributors.html
_includes/components/gc-most-requested/gc-most-requested.html
components/gc-contributors/index.json-ld
components/gc-contributors/samples/gc-contributors.html
components/gc-most-requested/samples/gc-most-requested.html

Two small content changes to align with DTO's guidance.

Content - Contributors and Most requested translation edit

---

wet-boew/footnotes/index.json-ld
wet-boew/formvalid/index.json-ld
wet-boew/menu/index.json-ld
wet-boew/multimedia/index.json-ld
wet-boew/overlay/index.json-ld
wet-boew/paginate/index.json-ld
wet-boew/prettify/index.json-ld
wet-boew/session-timeout/index.json-ld
wet-boew/share/index.json-ld

Added wet-boew working examples:
Footnotes
Form Validation
Menu
Multimedia
Overlay
Paginate
Prettify
Session-Timeout
Share

Wet-boew working examples #3

---

wet-boew/charts/index.json-ld
wet-boew/details-close/index.json-ld
wet-boew/dismissable-content/index.json-ld
wet-boew/exitscript/index.json-ld
wet-boew/tables/index.json-ld
wet-boew/wb-disable/index.json-ld
wet-boew/wb-postback/index.json-ld

Added wet-boew working examples::
charts
details-close
dismissable-content
exitscript
tables
wb-disable
wb-postback

Wet-boew working examples #4

---

_data/i18n.yml
wet-boew/equalheight/index.json-ld
wet-boew/filter/index.json-ld
wet-boew/lightbox/index.json-ld
wet-boew/stepsform/index.json-ld
wet-boew/tabs/index.json-ld
wet-boew/texthighlight/index.json-ld
wet-boew/twitter/index.json-ld
wet-boew/wb-randomize/index.json-ld

Added wet-boew working examples:
eqht-css
filter
lightbox
stepsform
tabs
texthighlight
twitter
wb-randomize

Wet-boew working examples #2

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.5.0

---

_data/design-patterns.json
_data/sites.json
design-patterns/gc-intro/index.json-ld
sites/layouts/default.html
sites/layouts/fluid.html
sites/main-page-title/_base.scss
sites/main-page-title/includes/main-page-title.html
sites/main-page-title/index.json-ld
sites/main-page-title/main-page-title-stacked-en.html
sites/main-page-title/main-page-title-stacked-fr.html

Main page title: adding stacked header variant

---

.eslintrc.json
components/wb-actionmng/actionmng.js
components/wb-fieldflow/fieldflow.js
components/wb-suggest/suggest.js
méli-mélo/2021-04-gcaem/js/x-combobox.js
méli-mélo/2021-04-gcaem/js/x-core-wb5.js
méli-mélo/2021-04-gcaem/js/x-wb5-datatable.js
méli-mélo/2023-10-clipboard/js/clipboard.js
sites/gcweb-menu/menu.js

Port of wet-boew/wet-boew#9793... and depends on it.
Doesn't cover "frozen" méli-mélo JS files.

ESLint: Indent switch case clauses

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.6.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.6.2

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.6.3

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v15.7.0

---

sites/footers/deprecated/footers-v7-en.html
sites/footers/deprecated/footers-v7-fr.html
sites/footers/footers-en.md
sites/footers/footers-fr.md
sites/footers/includes/footer.html
sites/footers/old-footers-en.html
sites/footers/old-footers-fr.html

Indigenous peoples -> Indigenous Peoples
Money and Finance -> Money and Finances
Version 8.0
Changes related to WET-497

Footer: text corrections

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v16.0.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v16.1.0

---

.github/workflows/cd.yml
.github/workflows/ci.yml
index-en.md
index-fr.md
package-lock.json
package.json

Release v16.1.1

---

index-en.md
index-fr.md
méli-mélo/th-empathy/meta.md
package-lock.json
package.json

Release v16.3.0

---

_data/templates.json
templates/news/index.json-ld
templates/news/news-doc-en.html
templates/news/news-doc-fr.html
templates/news/news-en.html
templates/news/news-fr.html

News: update news template

---

.github/dependabot.yml

Add dependabot to create PRs for GitHub Actions and NPM dependencies

chore: Add Dependabot for updates

---

Gruntfile.coffee
package-lock.json
package.json

Remove the unmaintained dependency, with the assumption that Dependabot will take over

chore: remove grunt-check-dependencies

---

package-lock.json
package.json

Port of wet-boew/wet-boew#9902's build change.

Build: Bump grunt-contrib-cssmin to v5.0.0

---

.github/workflows/cd.yml

Pages are already refreshed when deploying.

Github actions: remove unnecessary refresh of pages

---

docs/developing-en.md
docs/developing-fr.md
docs/evaluation-report/1-accessibility.html
docs/evaluation-report/2-wetplugin-gcweb2.html
docs/implementing-en.html
docs/implementing-fr.html
docs/index.html
docs/layouts/acr_wrote_en-en.html
docs/layouts/acr_wrote_en-fr.html
docs/layouts/assessment_wrote_en-en.html
docs/release/v5.0-en.html
docs/temp-v5issue.html
docs/test-case-1.html
docs/test-menu.html
docs/v5-migration.html

Took a pass with cSpell for non-functional typos

chore: typo cleanup in docs

---

wet-boew/charts/index.json-ld
wet-boew/geomap/demo/config-fr.js
wet-boew/geomap/demo/configwms-fr.js
wet-boew/geomap/geomap-en.html
wet-boew/geomap/geomap-fr.html
wet-boew/geomap/geomap-v4.0.30-en.html
wet-boew/geomap/geomap-v4.0.30-fr.html
wet-boew/geomap/v4.0.30/demo/config-fr.js
wet-boew/geomap/v4.0.30/demo/configwms-fr.js
wet-boew/multimedia/index.json-ld
wet-boew/toggle/reports/pre-a11y-1.json
wet-boew/wb-jsonmanager/jsonmanager-doaction-fr.html

Took a pass with cSpell for non-functional typos

chore: typo cleanup in wet-boew

---

.github/workflows/ci.yml
CONTRIBUTING.md
Gruntfile.coffee
README.md
_includes/alert-community-stable.html
_layouts/thématique-fr.html
index-en.md
index-fr.md
thématique/gc-thématique-fr.html

Took a pass with cSpell for non-functional typos

chore: typo cleanup for misc files

---

Gruntfile.coffee
méli-mélo/2021-04-gcaem/css/mandatetracker.css
package-lock.json
package.json
stylelint.config.js

Copied the setup from the `wet-boew` repo, and disabled the other failing rules. Only fixed the parsing error in the CSS files, not any of the other ones.

build: Add Stylelint setup from wet-boew

---

components/wb-actionmng/actionmng.js
components/wb-fieldflow/fieldflow.js

Replace deprecated jQuery `$.isArray` for JavaScript native `Array.isArray` for jQuery4 compatibility

Replace deprecated $.isArray

---

package-lock.json
package.json

I think a bunch of these were copied from WET originally, but are no longer referrenced in the Gruntfile. Maybe some of these are still required to sub-build WET recursively, but there may be version conflicts with that approach.

build: remove unused devDependencies

---

.github/ISSUE_TEMPLATE/request-en.md
.github/ISSUE_TEMPLATE/requete-fr.md
.markdownlint.json
docs/developing-fr.md

Enabled the rule and manually changed the bold blocks to H2s

build: enable MD036

---

Gruntfile.coffee
package-lock.json
package.json
sites/theme.scss

Updated the broken `includePaths` to `loadPaths`

build: update grunt-sass to v4

---

sites/footers/_base.scss

Fixed footer alignment with GCDS.

Footer: align with GCDS

---

_data/common.json
_data/components.json
_data/templates.json
sites/footers/demoted/footers-v8-en.html
sites/footers/demoted/footers-v8-fr.html
sites/footers/footers-en.md
sites/footers/footers-fr.md
sites/footers/includes/footer.html
sites/footers/old-footers-en.html
sites/footers/old-footers-fr.html

This pull request adds the Manage life events link to the site footer. Reference JIRA ticket WET-534.

Add manage life events link to site footer

---

templates/news/deprecated/news_v.4.0.1-en.html
templates/news/deprecated/news_v.4.0.1-fr.html
templates/news/news-doc-en.html
templates/news/news-doc-fr.html

Move Features section below search results on news template for GCWeb
For WET-552 ticket

Move Features section below search results on news template for GCWeb

---

components/baseline/_wb-mltmd.scss
sites/baseline/_scaffolding.scss
stylelint.config.js

Minor Stylelint issue that could be autofixed

build: enable Stylelint selector-not-notation

---

components/gc-chckbxrdio/_base.scss
stylelint.config.js

build: enable Stylelint hue-degree-notation

---

sites/footers/demoted/footers-v8.1-en.html
sites/footers/demoted/footers-v8.1-fr.html
sites/footers/footers-en.md
sites/footers/footers-fr.md
sites/footers/includes/footer.html
sites/footers/old-footers-en.html
sites/footers/old-footers-fr.html

Updated the life events links in the footer.
Related to WET-556

Footer: updating life events link

---

components/gc-minister/gc-minister-multiple-en.html
components/gc-minister/gc-minister-multiple-fr.html
components/gc-minister/index.json-ld
components/gc-minister/samples/gc-minister-multiple.html
templates/institutional-landing/index.json-ld
templates/institutional-landing/institutional-landing-multiple-en.html
templates/institutional-landing/institutional-landing-multiple-fr.html

Gc-minister component: creating working example with three columns and small images
Related to WET-559

Gc-minister component: creating working example with three columns and small images

---

index-en.md
index-fr.md
package-lock.json
package.json

Updates to index and package files for GCWeb release v17.0.0.

Release v17.0.0

---

_data/templates.json
templates/theme/_base.scss
templates/theme/_screen-lg-min.scss
templates/theme/_screen-md-min.scss
templates/theme/_screen-sm-max.scss
templates/theme/index.json-ld
templates/theme/theme-en.html
templates/theme/theme-fr.html
templates/theme/theme-youth-en.html
templates/theme/theme-youth-fr.html
templates/theme/theme.js

Some selector adjustments for easier integration into Canada.ca.

Theme: selectors adjustments

---

méli-mélo/2025-06-math-grid/math-grid.css

-Change:  Add separation to rows rather than padding of cells, and to fix override issue
-How this affects design: Adds no visual difference, except when using borders, borders will now have better separation.

updated spacing class to separate rows by px.

---

components/gc-srvinfo/gc-srvinfo-fieldflow-en.html
components/gc-srvinfo/gc-srvinfo-fieldflow-fr.html
components/gc-srvinfo/index.json-ld

Service and Information component: new variation with drop-down list using FieldFlow.
Related to WET-564

Service and Information component: variation with drop-down list using FieldFlow

---

thématique/gc-thématique-en.html
thématique/gc-thématique-fr.html

GCWeb thematic expiration date - content update

---

_data/components.json
_data/templates.json
_includes/components/gc-minister/gc-minister-multiple.html
_includes/components/gc-minister/gc-minister-special-cases.html
_includes/components/gc-minister/gc-minister-two-ministers.html
_includes/components/gc-minister/gc-minister.html
templates/ministerial/demoted/ministerial-en-V2.html
templates/ministerial/demoted/ministerial-fr-V2.html
templates/ministerial/demoted/ministerial-reduced-en-V2.html
templates/ministerial/demoted/ministerial-reduced-fr-V2.html
templates/ministerial/demoted/parliamentary-secretaries-reduced-en-V2.html
templates/ministerial/demoted/parliamentary-secretaries-reduced-fr-V2.html
templates/ministerial/index.json-ld
templates/ministerial/ministerial-doc-en.html
templates/ministerial/ministerial-doc-fr.html
templates/ministerial/ministerial-en.html
templates/ministerial/ministerial-fr.html
templates/ministerial/ministerial-reduced-en.html
templates/ministerial/ministerial-reduced-fr.html
templates/ministerial/parliamentary-secretaries-reduced-en.html
templates/ministerial/parliamentary-secretaries-reduced-fr.html

- This PR updates the ministerial and parliamentary secretary profile templates in English and French.
- Refreshes content and examples in templates/ministerial/*
- Aligns with current guidance and terminology

Content - Update ministerial and parliamentary secretary profile templates

---

_data/components.json
_includes/components/gc-minister/gc-minister-multiple.html
_includes/components/gc-minister/gc-minister-special-cases.html
_includes/components/gc-minister/gc-minister-two-ministers.html
_includes/components/gc-minister/gc-minister.html
components/gc-dwnld/_base.scss
components/gc-dwnld/demoted/gc-dwnld_v1-en.html
components/gc-dwnld/demoted/gc-dwnld_v1-fr.html
components/gc-dwnld/gc-dwnld-doc-en.html
components/gc-dwnld/gc-dwnld-doc-fr.html
components/gc-dwnld/gc-dwnld-en.html
components/gc-dwnld/gc-dwnld-fr.html
components/gc-dwnld/index.json-ld

Download link: new pattern

---

index-en.md
index-fr.md
package-lock.json
package.json

Updated index and package files for release of GCWeb v17.3.0.

Release v17.3.0

---

index-en.md
index-fr.md
package-lock.json
package.json

Release v17.6.0
