wet-boew/GCWeb

src/secondary-menu/_base.scss

Contrast ratio fails at 3.0:1, fixed to 60% and achieves 5.7:1.

Secondary menu: Fix hover issue for contrast ratio on GCWeb theme.

---

Gruntfile.coffee
package.json

Move to the libsass 3.3.x core to resolve old extend issues.
Basic diff of changes can be found https://gist.github.com/nschonni/03e8e6f675e595869617. Their are selector changes in a few places, but these appear to be bugs with the old node-sass, since the selectors match the Ruby Sass when comparing on Sassmeister.
The precision was increased to 10 for now, but the later Bootstrap-Sass releases only require 8.
This also frees developers to update to Node 0.12 or iojs.

Build: Update to Grunt-Sass 1.0.0

---

src/_defaults.scss

Prevents Firefox from sometimes misinterpreting 1.25 as 1.25px. That kind of unit-less measurement is normally ignored by browsers.

CSS: Added missing unit measurement for H1 margin-top property.

---

site/includes/fullmenu-en.hbs
site/includes/fullmenu-fr.hbs

This ensures that en dashes are used consistently across all of those kinds of links. Previously, a mix of minus hyphens and en dash characters were used.

Menu: Replaced minus hyphens with en dashes in "– More/Autres" links.

---

site/pages/ministerial-en.hbs
site/pages/ministerial-fr.hbs

* Added a ``<section>`` element around the "Contact information" heading and its associated content.
* Replaced a hollow ``<section>`` with a ``<div>`` in the "Recent announcements" section. Prevents HTML 5.1 validation warnings about heading-less sections.

Site: Fixed sectioning issues in Ministerial profile page.

---

src/_defaults.scss

Makes GCWeb consistent with other WET themes in this respect. As a result, table THs now appear bolded in IE8-11 (in line with every other browser).
Fixes #1040 and resolves wet-boew/wet-boew#7170.
@masterbee I noticed you originally introduced ``font-weight: 300;`` via commit c2723ef. Would you have any concerns with my PR removing it? From what I can tell, its removal doesn't change anything at all in other browsers. Just makes tables less strange-looking in IE :).

Theme: Removed body font-weight property from CSS.

---

site/pages/advancedservice/index-en.hbs
site/pages/advancedservice/index-fr.hbs
site/pages/advancedservice/page2-en.hbs
site/pages/advancedservice/page2-fr.hbs
site/pages/advancedservice/page3-en.hbs
site/pages/advancedservice/page3-fr.hbs
site/pages/advancedservice/page4-en.hbs
site/pages/advancedservice/page4-fr.hbs
site/pages/advancedservice/page5-en.hbs
site/pages/advancedservice/page5-fr.hbs
site/pages/advancedservice/page6-en.hbs
site/pages/advancedservice/page6-fr.hbs

Prevents broken layouts when one or more ToC links contain significantly longer step names than the others.
I've provided some screenshots below to show off the scenarios this PR fixes...
**1)**
**Small view - before:**
**Small view - after:**
**2)**
**Medium view - before:**
**Medium view - after:**

Advanced service initiation pages: Added clear left classes to ToC links.

---

Gruntfile.coffee

When running ``grunt`` or ``grunt dist`` in GCWeb, ``src/fonts/_base.scss`` currently gets copied into ``dist/fonts/_base.scss``. That file is also present in GCWeb 4.21's release package. This PR will prevent it from getting copied in the first place.
@LaurentGoderre @nschonni @shawnthompson FYI.

Theme: Prevent fonts folder's .scss file from getting copied into dist.

---

src/ie8-theme.scss
src/priorities/_print.scss
src/theme.scss

Reasoning:
* It's not main content (it's outside the ``<main>`` element). If anyone wants to print out a particular activity/initiative, in practice the odds are high that they'd click the link to it in their browser to open up that item's dedicated page, then print that out.
* It usually adds 1-2 extra pages when printing (depending on how many items are used).
* Its current print layout looks broken. If a given activity/initiative splits across pages, it looks really strange and creates large empty gaps of space.
CC @nicolasraymond @shawnthompson

Theme: Hid GC activities and initiatives in print view.

---

src/secondary-menu/_print.scss

It was originally hidden prior to #1058 (dc150a9059f461e38c081b65675c077e0c96b47f). One of its changes renamed #wb-sec to #gc-sec in secondary-menu/_print.scss. But #gc-sec doesn't exist, which resulted in the secondary menu becoming unveiled when printing. This commit renames it back to #wb-sec.
Fixes #1204.
CC @rlambert27 @karinne @shawnthompson

Secondary menu: Hid secondary menu in print SCSS.

---

site/data/i18n/fr.json

GCWeb doesn't contain an English version of that variable. Both variables already exist in wet-boew and are inherited from it when building GCWeb.

i18n: Removed French "tmpl-about-site" variable.

---

site/includes/corp-info-roles.hbs
site/includes/corp-info.hbs

Div elements using a class="col-md-4" attribute were previously wrapped around each role's section element. Since there's only one section for each div, the div elements aren't necessary.
This commit removes the divs in question and moves their class attributes onto the sections themselves.

Corporate information includes: Simplified div/section markup.

---

site/pages/advancedservice/index-en.hbs
site/pages/advancedservice/index-fr.hbs
site/pages/advancedservice/page2-en.hbs
site/pages/advancedservice/page2-fr.hbs
site/pages/advancedservice/page3-en.hbs
site/pages/advancedservice/page3-fr.hbs
site/pages/advancedservice/page4-en.hbs
site/pages/advancedservice/page4-fr.hbs
site/pages/advancedservice/page5-en.hbs
site/pages/advancedservice/page5-fr.hbs
site/pages/advancedservice/page6-en.hbs
site/pages/advancedservice/page6-fr.hbs

The ToC's current page links use the "active" class to create a visual highlighting effect on them. However, apart from that class, those links were previously coded identically to all non-current links. Meaning visual design was being used to convey meaningful information without any supporting HTML markup.
This change removes the href attribute from current page links to give them a semantic meaning. The HTML spec considers a elements without href attributes to be placeholders for where links might've gone if they had been relevant.

Advanced service initiation pages: Changed ToC's current page links into placeholder ones.

---

site/pages/advancedservice/index-fr.hbs
site/pages/advancedservice/page2-en.hbs
site/pages/advancedservice/page2-fr.hbs
site/pages/advancedservice/page3-en.hbs
site/pages/advancedservice/page3-fr.hbs
site/pages/advancedservice/page4-en.hbs
site/pages/advancedservice/page4-fr.hbs
site/pages/advancedservice/page5-en.hbs
site/pages/advancedservice/page5-fr.hbs
site/pages/advancedservice/page6-en.hbs
site/pages/advancedservice/page6-fr.hbs

The first English page's ToC uses a class called "gc-stp-stp", but its French counterpart and pages 2-6 were using "mrgn-tp-md brdr-bttm". As a result of that inconsistency, the top of the right panel was "sticking" against the ToC's bottom border in all of the latter pages.
This commit updates all affected pages' ToCs to use the "gc-stp-stp" class, which increases consistency and resolves the aforementioned spacing issue.

Advanced service initiation pages: Updated ToC list's class in most pages.

---

site/pages/advancedservice/index-en.hbs
site/pages/advancedservice/page2-en.hbs
site/pages/advancedservice/page3-en.hbs
site/pages/advancedservice/page4-en.hbs
site/pages/advancedservice/page5-en.hbs
site/pages/advancedservice/page5-fr.hbs
site/pages/advancedservice/page6-en.hbs

* Renamed all instances of "Step name / section page" to "Step / section page name" in the English versions of page 1 and pages 3-6.
* Revised first lorem ipsum paragraph in the English version of page 1 for consistency with its French counterpart.
* Removed first lorem ipsum paragraph from the English versions of pages 2-6 for consistency with their French counterparts.
* Added an opening bracket to the ToC's 6th list item in the English version of page 2.
* Removed a space prior to the closing bracket in all instances of "[Nom de la page de la section ou de l’étape ]" in the French version of page 5.

Advanced service initiation pages: Fixed content consistency issues.

---

site/pages/splashpage.hbs

The H1 heading in question previously contained a broken handlebars expression, which caused "{title}}" to appear in generated splash pages.
This commit adds an extra opening bracket to allow the aforementioned expression to resolve to "Canada.ca".

Splash page: Fixed H1 heading's content.

---

site/includes/brand.hbs
site/layouts/servermessage.hbs

A bilingual FIP image is situated in the top-right of all of GCWeb's pages. Until now, in all standard/server message page templates, the image's alt text was unilingual, which isn't an accurate representation of the text in the image.
This commit adds extra handlebars conditions to make the FIP's alt text bilingual depending on the current page language.
**PS:** The issue this PR fixes likely affects all pre-existing GCWeb implementations (e.g. Canada.ca, CDTS, web applications based on GCWeb, etc...).

Theme: Fixed header FIP image's incomplete alt text.

---

site/pages/splashpage.hbs

Affects the following strings:
* Government of Canada FIP alt text
* Language links
* Hidden Government of Canada headings
* Terms and conditions links (note: replaces "&" with "and" in English link)
* Canada wordmark alt text

Splash page: Replaced hardcoded text with relevant i18n variables.

---

src/plugins/fieldflow/basic-en.hbs
src/plugins/fieldflow/basic-fr.hbs
src/plugins/fieldflow/fieldflow-doc-en.hbs
src/plugins/fieldflow/fieldflow-doc-fr.hbs
src/plugins/fieldflow/fieldflow.js

Live workinng example: http://universallabs.org/wet/labs/gcweb-PR1244/index-en.html
**Improved list items selector**
Improved list items selector to be configured and to be outside the header/labeling block.
It fix the following scenario where it's expected that the second unordered list (outside the header block) be used instead of the unordered list in the header block.
```html
<div class="wb-fieldflow">
<div class="wb-fieldflow-header">
<p>Some text before the label.</p>
<p class="wb-fieldflow-label">The label</p>
<p>Some text after the label.</p>
<ul>
<li data-wb-fieldflow="ajax/ajax-1.html">sss(Set 1) Nunc sed mauris id nisi molestie porta at quis erat.</li>
<li data-wb-fieldflow="ajax/ajax-2.html">sss(Set 2) Vestibulum pretium tortor vel facilisis sodales.</li>
<li …
```

Fieldflow - Improved list items selector and new config to prevent inserting required label

---

src/ie8-theme.scss
src/search/_screen-sm-max.scss
src/search/_screen.scss
src/theme.scss

In medium/large views, the search field/button's layout used to rely on space/line break/tab characters being present in-between their elements in HTML markup. Their presence "filled" in the left side of the search button to make it look square-shaped. But in pages that use minified HTML, the space disappeared, which hindered the button's layout.
It turns out that the search feature's small view and under SCSS file contained selectors that eliminated the space in noscript/wbdisable mode.
This commit moves the aforementioned selectors into a screen SCSS file, adds left/right margins on the button to retain its square shape and adjusts the button's height to match the search field. Combined, these allow the button to always remain square-shaped and flush with its input field.
Related to …

Search: Fixed search button layout issues.

---

src/footer/_base.scss
src/footer/_screen-md-min.scss
src/footer/_screen-sm-max.scss
src/footer/_screen-xxs-max.scss
src/ie8-theme.scss
src/theme.scss

* Stopped nesting li selectors inside ul selectors.
* Moved certain selectors into a medium view and over file.
* Removed small view and under file's li:first-child:before selector.
* Removed extra-extra small view file's redundant li margin-bottom selector.
* Removed empty lines in-between certain nested parent selectors.

Footer: Simplified about list's SCSS selectors.

---

src/_variables.scss
src/footer/_base.scss
src/footer/_screen-md-min.scss

The "About this site" list's layout used to rely on space/line break/tab characters being present in-between li elements in the list's HTML markup. But that didn't lend itself to pages that use minified HTML. The horizontal spacing between the list's items looked even in unminified pages, but looked off in minified ones.
This commit changes the list's SCSS to always use an even amount of spacing, regardless of whether HTML has been minified.
**Screenshots:**
* **Before (minified):** ![before_minified](https://user-images.githubusercontent.com/1907279/27187978-aae718f6-51ba-11e7-9bc5-c4d25c705043.png)
* **Before (unminified):**  ![before_unminified](https://user-images.githubusercontent.com/1907279/27187971-a94b1fba-51ba-11e7-8244-6f4422df5059.png)
* **After (minified and unminified):** …

Footer: Made about list compatible with minified HTML.

---

src/menu/_base.scss
src/overlay/_base.scss

See close button in the mobile menu and in the overlay working example
http://universallabs.org/wet/labs/fix-overlay-close/gcweb/unmin/index-en.html
http://universallabs.org/wet/labs/fix-overlay-close/gcweb/unmin/demos/overlay/overlay-en.html

fix background-color for menu overlay close button

---

site/includes/footerbrand.hbs

When the footer was revised as a part of #1132, the width of the wordmark's grid was reduced to "col-md-2". But that caused the wordmark to significantly overflow beyond its container in medium view's minimum widths (992-1011 pixels), which introduced an horizontal scrollbar.
This commit eliminates the scrollbar by increasing the wordmark's grid width to "col-md-3" and adjusts the rest of the grid layout accordingly. It also keeps the original 10/2 grid layout in large view to maximize the "About this site" list's available width.
On a side note, in large view, the wordmark slightly overflows its "col-lg-2" grid, but not enough to go past the far right edge of the grid's right padding. So it's not significant-enough to cause an horizontal scrollbar to appear.

Footer: Increased the Canada wordmark's grid width in medium view.

---

site/data/i18n/en.json
site/data/i18n/fr.json
site/includes/skiplinks.hbs

Prior to #1132, the first heading within the wb-info ID's container was called "About this site". As a part of #1132's changes, the footer was restructured into two sections of links ("About government" and "About this site"). As a result of those changes, wb-info's first heading changed to "About government"... but its skip link was never updated. Ever since then, the "Skip to 'About this site'" skip link has technically been pointing to the "About government" heading.
This commit fixes that inconsistency by renaming the "Skip to 'About this site'" link to "Skip to 'About government'".

Skip links: Changed "About this site" to "About government".

---

site/includes/datemodified.hbs
src/_defaults.scss

The report a problem dropdown box's width was previously thinner than the summary button that directly precedes it. Bootstrap's "row" class was being misused to increase its width, but it still wasn't enough. The "row" class' negative left/right margins differ from the summary's margins.
This commit makes the dropdown box's width consistent with the preceding summary. It removes the unnecessary "row" class and overrides the "well" class' margins to rely on the same SCSS variable that's used to generate the summary element's left/right margins. These changes are backwards-compatible with GCWeb 4.0.26 and under.
**Screenshots:**
* **Before:**
* **After:**
**PS:**
PR #1290 should be merged in before this one. Once that's merged, merge conflicts will appear in this PR and it'll need to be …

Report a problem: Fixed dropdown box's width.

---

site/includes/promotion1.hbs
site/pages/campaign-en.hbs
site/pages/campaign-fr.hbs
site/pages/event-en.hbs
site/pages/event-fr.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs
site/pages/news-en.hbs

The promotion1 include only contains a carousel. It doesn't use a grid layout, so the "row" class was being misused. That class was also causing the include's carousel to become wider than the content area and "touch" that area's far left/right edges. It was especially noticeable in extra-small view and under.
This commit removes the "row" div and affects the following page templates:
* Campaign (example 1)
* Event
* Home
* News (English-only)

Promotion1 include: Removed "row" div.

---

site/includes/skiplinks.hbs

In WET's other themes, the footer and its associated skip link are hidden in extra-small view and under. #1132 made GCWeb's entire footer visible in the aforementioned view. But the footer's skip link wasn't updated accordingly. So it remained hidden in smaller views ever since.
This commit makes the footer's skip link visible in all views.

Skip links: Made footer link visible in all views.

---

site/includes/byline.hbs
site/pages/ministerial-en.hbs
site/pages/ministerial-fr.hbs

Most of GCWeb's sample links were already doing this, but a handful weren't (their brackets were situated outside of the links).

Sample links: Moved square brackets into link text.

---

src/_defaults.scss

When expanding details elements that use summaries styled as default buttons, their borders were previously changing in an undesirable manner.
Specifically:
* Button borders were disabled. This caused the buttons, their content and their outlines to shift positions. If content was spread across multiple lines, it could even cause words to "jump" to a preceding line.
* Bottom border radiuses were disabled. This caused the bottom of the buttons to become square-shaped upon being pressed.
* A light grey bottom border was added.
This commit fixes it by adding SCSS overrides to restore the default button style's intended layout on affected summary elements.
**Screenshots (Firefox Developer Edition 57.0b6):**
* **Collapsed ``details`` element (for reference):**
* **Expanded ``details`` element …

Theme: Fixed layout issues with summaries styled as default buttons.

---

src/_variables.scss

Bootstrap 3.3.1 contains an SCSS colour variable called $gray-dark. It's sometimes used as a text colour against white backgrounds or as a background colour against white text.
Bootstrap's default value for $gray-dark fails WCAG 2.0 AA's contrast ratio requirements when used against white text/backgrounds. To meet those requirements, wet-boew/wet-boew#5600 darkened that variable's value in WET's core SCSS.
wet-boew/wet-boew#5600's fix achieved a 4.5:1 contrast ratio in WET themes that use white background colours. But in GCWeb, the fix only produced a 4.3:1 contrast ratio, since that theme uses a light grey background colour.
This commit further darkens $gray-dark in GCWeb to meet WCAG 2.0 AA's contrast ratio requirements. It depends on wet-boew/wet-boew#8198.
Credit goes to @donmcdill …

Theme: Darkened light grey colour SCSS variable.

---

src/plugins/data-json/data-json-doc-en.hbs
src/plugins/data-json/data-json-doc-fr.hbs
src/plugins/data-json/data-json.js
src/plugins/data-json/demo/data-en.json
src/plugins/data-json/demo/data-fr.json
src/plugins/data-json/template-en.hbs
src/plugins/data-json/template-fr.hbs
src/plugins/deps/template.js

Data-JSON: Add support to template by selecting a JSON object instead of an array and IE11 bug fix with sub-template.
Working example: 
* http://universallabs.org/wet/labs/gcweb-2017-11-21/unmin/demos/data-json/template-en.html

Data-JSON: Add support to template by selecting JSON object + bug fix

---

site/includes/focuson.hbs
site/includes/task.hbs
site/includes/theme-topic.hbs
site/includes/topic-subtopic.hbs
site/pages/campaign2-en.hbs
site/pages/campaign2-fr.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs

That class wasn't associated to any SCSS styles. It also wasn't used consistently across either GCWeb nor real-world implementations of that theme (including the MWS).
If it solely existed as a placeholder class to make it possible to easily modify the layout of all doormat links in the future, it was unable to fully achieve that objective since it was missing from many pages that use those kinds of links.
@lucas-hay @masterbee @shawnthompson Thoughts?

Theme: Removed all references to the "gc-drmt" class.

---

site/includes/corp-info.hbs
site/includes/focuson.hbs
site/pages/components-en.hbs
site/pages/components-fr.hbs
site/pages/home-en.hbs
site/pages/home-fr.hbs
site/pages/institution-arms-en.hbs
site/pages/institution-arms-fr.hbs
site/pages/institution-contact-en.hbs
site/pages/institution-contact-fr.hbs
site/pages/institution-en.hbs
site/pages/institution-fr.hbs
site/pages/localnav/index-en.hbs
site/pages/localnav/index-fr.hbs
site/pages/ministerial-en.hbs
site/pages/ministerial-fr.hbs
site/pages/news-en.hbs
site/pages/organizational-arms-en.hbs
site/pages/organizational-arms-fr.hbs
site/pages/organizational-en.hbs
site/pages/organizational-fr.hbs
site/pages/theme-en.hbs
site/pages/theme-fr.hbs
site/pages/topic-en.hbs
site/pages/topic-fr.hbs

The same end result of the empty clearing divs ("clearfix" class" was replicated and replaced by using equal heights. 
There were also various other instances of clr-xxx-xxxx classes that really served no purpose so were removed.
@duboisp please have a look and let me know what you think

removed all empty clearing divs (clearfix and clr-xxx-xxx classes)

---

site/includes/brand.hbs
site/includes/footerbrand.hbs
site/layouts/servermessage.hbs
site/pages/splashpage.hbs
src/banner/_base.scss
src/messages.scss

* Port of wet-boew/wet-boew#8282.
* Related to wet-boew/wet-boew#8276.
* Modifies SCSS to increase the bottom margins on the FIP images to replicate the empty space that was previously appearing below their object element containers.

Theme: Reference SVG logos with img element instead of object.

---

Gruntfile.coffee

This should probably be more dynamic, but this fixes the mismatched version for now.

build: Update hardcoded oldIE jQuery version

---

src/share/_print.scss

Previously, if a user expanded the "Report a problem on this page" dropdown in a browser and subsequently printed the page they were on, the dropdown's expanded content would appear in the printout. However, the expanded content served no purpose in that context. Furthermore, since the "Report a problem on this page" button is hidden when printing, the purpose of the expanded content wasn't clear.
This change prevents the expanded content from ever appearing in printouts.

Theme: Hid expanded report a problem dropdowns when printing.

---

site/pages/localnav/index-en.hbs
site/pages/localnav/index-fr.hbs
site/pages/ministerial-en.hbs
site/pages/ministerial-fr.hbs

This pull request when added addresses two items identified in Issue #1305 : 
1. Remove the remaining `clr-rght-md` and `clr-rght-lg`
2. Fixing this content block: where column is not child of a row
In addition: 
3. The Ministerial profile page templates were brought more in line with how they appear in the [Content and IA Spec version 1.5](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/templates-detailed-specifications/ministerial-profile-pages.html).
Notes: 
1. I had to change the pattern of the Date and Time text in the News section (line 52 of the English Ministerial hbs file) to be an actual time `2018-06-05 19:00` because the html linter did not like the pattern `YYYY-MM-DD hh:mm` inside a …

Fix part of #1305: remove pull right classes and update ministerial template 

---

site/pages/dept-en.hbs
site/pages/dept-fr.hbs
site/pages/index/longindex-en.hbs
site/pages/index/longindex-fr.hbs
site/pages/topic-fr.hbs

References to the "pagetag" class, property and include were removed from all pages in #1155.
However, #1155 didn't remove the property from the French topic page template. Furthermore, #1297 inadvertently re-introduced the class into the departments and agencies page. The class was also present in #1372's long index pages.

Theme: Removed leftover references to to the "pagetag" class/property.

---

.editorconfig

* Added dot-prefixed/JSON/MD formats and Gemfile.lock to 2 space indentation overrides. Overall, those files already use 2 spaces more heavily than tabs.
* Removed package.json from the aforementioned override. It'll continue to be covered via the JSON override.
* Removed redundant rules from 2 space indentation overrides. They're already set in the global overrides.
* Added unset overrides for the font SVG file. Should prevent other overrides from affecting that file if it's updated in the future.
* Port of wet-boew/wet-boew#8448 and wet-boew/wet-boew#8450.

EditorConfig: Added .*/JSON/MD/Gemfile.lock overrides and exempted font SVG.

---

site/pages/campaign2-en.hbs
site/pages/campaign2-fr.hbs

* Moved "hght-inhrt" class from list items to the links within them.
* Removed "mrgn-bttm-lg" class from the brief description paragraphs. That class no longer serves any purpose since the inherited heights make the link boxes taller.
* Fixes wet-boew/wet-boew#8483.

Campaign example 2: Fixed equal heights implementation.

---

package-lock.json

Specific changes:
* Changed "requires" fields to use version ranges derived from each dependency's package.json file.
* Added "from" field for git dependencies.
* Added entry for "magnific-popup" (was previously missing).
Notes:
* The latest versions of node.js come with npm 6.4.1. So all newer versions of node.js expect the new style.
* Running npm install in older versions of npm will reconvert the Git working tree's package-lock.json file to the older style.

package-lock.json: Updated to npm 5.10/6.x-friendly style.

---

package-lock.json
package.json

GCWeb's package.json file previously specified "wet-boew/wet-boew" as a dependency, without a tag or commit hash. As a result, running npm install would cause package.json's wet-boew dependency to resolve to that project's latest commit and modify the working tree's version of package-lock.json to specify wet-boew's latest commit hash.
This commit modifies GCWeb's package files to specify WET 4.0.29's tag. That way, the version of WET that'll be used will be predictable and prevent package-lock.json's wet-boew entries from getting modified when a user installs the build system.

Build: Depend on a specific version of WET (4.0.29).

---

site/includes/sitemenu.hbs
site/pages/component/list-en.hbs
site/pages/component/list-fr.hbs
site/pages/evaluation-report/1-accessibility.hbs
site/pages/gcweb-theme/index.hbs
site/pages/gcweb-theme/temp-v5issue.hbs
site/pages/gcweb-theme/v5-migration.hbs
site/pages/home/index.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs
src/_defaults.scss
src/_variables.scss
src/breadcrumb/_base.scss
src/buttons/_base.scss
src/menu/_base.scss
src/menu/_print.scss
src/menu/_screen-md-min-to-screen-md-max.scss
src/menu/_screen-md-min.scss
src/menu/_screen-sm-max.scss
src/menu/_screen-xs-max.scss
src/plugins/menu/menu.js

The menu name was changed from ```gcweb-v2``` to ```gcweb-menu```. A note was added in the migration instruction.

Renaming code name v2 for v5 along with the menu plugin and updated gcweb home page intro

---

site/pages/gcweb-theme/index.hbs
site/pages/gcweb-theme/test-menu.hbs
src/plugins/menu/menu.js

This fix an issue that prevent to operate the main menu in IE11 by using the NVDA screen reader.
Closes https://github.com/wet-boew/wet-boew/issues/8556
Remaining test:
* Chrome with NVDA
* Chrome with Jaws18
* Re-test with Firefox, IE and Edge
Test page: http://universallabs.org/wet/labs/gcwebmenu/content-en.html

Menu fix when navigating with a screen reader

---

src/carousel/_base.scss

wet-boew/GCWeb#917 modified GCWeb's carousels to hide link underlines by default and only show them on hover. Later on, one of wet-boew/wet-boew#7683's changes caused WET's carousel link selectors to become more specific than GCWeb's overrides. So most carousel links started appearing as underlined by default in GCWeb again.
However, GCWeb's overrides continued to affect figcaptions that contained links inside them. This caused transcript links in carousels that contain multimedia players to not appear as underlined. Without the underlines, those links looked like plain text.
This commit removes GCWeb's old overrides to prevent the aforementioned links from appearing as plain text.
**Screenshots of [GCWeb's carousel demo page](https://wet-boew.github.io/themes-dist/GCWeb/demos/tabs/tabs-ca …

Carousel: Removed link underline overrides.

---

src/carousel/_base.scss

GCWeb sets 10px top and bottom margins on the multimedia player. Due to conflicts with the carousel's CSS, the top margin was appearing as a light grey border above media players situated within carousels.
This commit removes the top margin in the aforementioned context to prevent that behaviour.
**Screenshots of [GCWeb's carousel demo page](https://wet-boew.github.io/themes-dist/GCWeb/demos/tabs/tabs-carousel-en.html)...**
**Before:**
**After:**

Carousel: Removed media player top's margin.

---

package-lock.json
package.json

After this merged, it will be possible to merge PR #1520 
Also, it includes a build script issue with: Plugin Share/Sprite: Fix build blocking condition

WET-BOEW dependance - Bump to v4.0.31-development+2019-05-08 build

---

site/pages/experimental-en.hbs
site/pages/experimental-fr.hbs

Wrapped up my stretched link example inside an experimental class, "cleaned" the hyperlinks, added more details to that example and did the French translation in the documentation (example excluded).

Streched link: Example fix and more documentation

---

package-lock.json
package.json
site/includes/sitemenu.hbs
site/pages/gcweb-theme/release/dev-build.hbs

Because this is a template change, this change will major increase the version number of GCWeb

Major - Fix broken theme link in the default menu in the template

---

Gruntfile.coffee
package-lock.json
package.json

**Specific changes:**
* Updated grunt-sass dependency to ^3.0.2
* Other changes required by grunt-sass 3.x:
* Added node-sass ^4.12.0 dependency
* Modified Gruntfile.coffee for compatibility
**Notes:**
* Produces a nearly-identical theme.css file compared to before:
* CSS properties containing values of "rgba(0, 0, 0, 0)" are now generated as "transparent" instead
* Makes GCWeb compatible with Node 10
* Should make GCWeb's node-sass dependency compatible with Node 12
* Port of wet-boew/wet-boew##8687
@duboisp FYI

Build: Update grunt-sass and related changes

---

Gruntfile.coffee
package-lock.json
package.json

This is a partial port of wet-boew/wet-boew#8679.
Didn't port the CSSLint update (nor its rule adjustments) since GCWeb doesn't currently use it. I didn't feel like it'd be appropriate to introduce CSSLint into GCWeb a as a part of this PR.
@duboisp FYI

Build: Update grunt-banner and eliminate duplicate CSS charsets

---

site/pages/gcweb-theme/test-case-1.hbs

**Notes:**
* Didn't add any autocomplete attributes to the "Labels"/"Inputs" sections due to lack of context.
* Some fields are now set to type="email" and autocomplete="username"... The HTML spec seems to disallow it and the validator consequently produces an error. But it might not be the spec's true intent.
Related to wet-boew/wet-boew#8692

Form test cases: Add autocomplete attributes

---

site/pages/gcweb-theme/index.hbs
site/pages/index-en.hbs
site/pages/index-fr.hbs

The previous behaviour didn't result in broken links (the build seems to automatically rename .hbs extensions to .html), but wasn't consistent with how the vast majority of links to built pages are coded to use .html extensions.

Site: Rename .hbs links to .html

---

package-lock.json
package.json

Decreases build times due to an updated glob sub-dependency. Windows gets a substantial speed boost. Linux probably also benefits.
From a cold boot in Windows, grunt dist used to take ~4.75 minutes... now it only takes ~3.75 minutes.
This PR's generated dist folder is identical to before.
The newer version of CoffeeScript used in grunt 1.0.4 doesn't appear to introduce any breaking changes to Gruntfile.coffee.
Port of wet-boew/wet-boew#8690

Build: Update grunt to ~1.0.4

---

site/pages/video-en.hbs
site/pages/video-fr.hbs

This is another take on what was done in #1576.
GCWeb contains copies of most (all?) of the WET repo's plugin demo pages, documentation and supporting files. So it makes more sense for the video example page's poster image references to be relative to GCWeb instead of referencing an external repo (wet-boew).

Video example: Use repo's copies of poster images

---

site/layouts/splashpage.hbs

The splash page layout file's "description-en" and "description-fr" variables previously contained typos, which prevented their values from appearing in the generated splash page's metadata.
This commit corrects the typos to allow their real values to properly appear in the generated splash page.

Splash page: Fix typos in meta description vars

---

Gruntfile.coffee
package-lock.json
package.json

Updates grunt-html to ^11.1.1 and adjusts several ignore rules in its associated task (htmllint). A few new ignore rules have been added, whereas many outdated ones have been removed.
This is a port of wet-boew/wet-boew#8728.
**PS:**
I copied the following line comment from wet-boew/wet-boew#8373 for the sake of consistency:
> ``# TODO: Should be removed and fixed now that HTML5 specs updated``
Thanks @nschonni :)

Build: Update grunt-html to ^11.1.1 and revise htmllint ignore rules

---

package-lock.json
package.json

GCWeb's build system previously couldn't be successfully installed in node.js 12.x due to its wet-boew/wet-boew#v4.0.31 dependency lacking wet-boew/wet-boew#8687's updates.
This commit resolves it by updating the wet-boew dependency to its latest commit. I specified a specific commit hash in package.json to prevent npm install from attempting to always update to the latest wet-boew commit (which would pollute package-lock.json once future commits get added to wet-boew).

Build: Update wet-boew to latest commit

---

site/includes/languagetoggle.hbs

Brings GCWeb in line with wet-boew (which has been using ``hreflang`` since wet-boew/wet-boew#4288).

Theme: Add hreflang attribute to language toggle links

---

Gruntfile.coffee

This aborts the build if the bootlint task runs into any warnings (in line with how the other linters work). It'll show all issues it found before failing.
Should make it much more obvious if any future changes introduce bootlint warnings.
Partial port of wet-boew/wet-boew#8739 (GCWeb already fails on bootlint errors).

Build: Fail on bootlint warnings

---

package-lock.json
package.json

Is blocked by an upcoming PR that introduces a new GC Features pattern and passes the build.

WET-BOEW Dependency Bump to v4.0.33

---

site/pages/gcweb-theme/release/v6.0-en.hbs
site/pages/gcweb-theme/release/v6.0-fr.hbs

Found non-escaped HTML markup in the commits list of v6.0 release notes.

Fix potential build breaker in hbs markup

---

.sass-lint.yml

Please remove the sasslint rule no-url-protocols: 1 to remove the warnings on grunt test sasslint:all task. 
This is preferable over removing the HTTPS import url protocol from _defaults.scss.

removed no-url-protocols rule to remove warnings from test

---

src/plugins/fieldflow/fieldflow.js

This is how fieldsets with normal-sized legends are supposed to be coded in WET.
Field flow was previously misusing the "h5" class in its fieldset legends to get a similar visual effect. But that method has error message overlapping issues in modern versions of GCWeb and won't benefit from any solutions for #1634 (like #1654 and #1676).

Field flow: Use "chkbxrdio-grp" class for fieldsets

---

site/pages/home-en.hbs
site/pages/home-fr.hbs

At 479px wide and down, you get a lighter, more vertical than horizontal image as the background on the home page. This is better adapted for mobile user and it consumes less data for them.

Home page: Have a smaller image for smaller device on the home page with bgimg-srcset

---

site/includes/brand.hbs
site/layouts/servermessage.hbs
site/pages/splashpage.hbs

- removed the span with GC text and RDFa name
- placed GC text in logo img alt
- supplemented RDFa name with a meta tag
Note: the img alt text is reflecting the brand text of the chosen language of page only. Logos are exempt from verbosity.
Related: https://github.com/wet-boew/GCWeb/issues/1670

Moving GC brand text to img alt

---

site/pages/gcweb-theme/v5-migration.hbs

This page was identified as unilingual in #1677's review.
I planned to add an ``isUnilingual`` variable and an extra condition for it... But it turns out that WET and GCWeb already have a built-in ``languagetoggle`` variable that does the same thing.
Things to note:
- The ``languagetoggle`` variable and its associated conditions expect its value to be a string. Several other similar variables work in the same way across WET/GCWeb.
- Without the language toggle section, GCWeb's header shifts upwards. It still looks fine, but the amount of space above the FIP and search field is reduced.

Migration page: Disable language toggle section

---

site/layouts/default.hbs

This was the only handlebars condition in the entire theme that specifically checked whether a boolean variable's value was "true". All other bool conditions use #if and only check whether they're truthy.

Theme: Simplify boolean condition in default page template

---

site/layouts/servermessage.hbs
site/pages/404-en-fr.hbs
site/pages/404-fr-en.hbs
site/pages/servermessage-en-fr.hbs
site/pages/servermessage-fr-en.hbs
site/pages/splashpage.hbs

This change updates wordmark code for consistency with #1673's FIP changes.
Specifically:
- The splash page's wordmark now uses an English alt attribute and hidden span elements for the French version's text alternative
- Bilingual server message pages now use bilingual textual equivalents for their wordmarks (they previously only used unilingual alt attributes)
- Unilingual server message pages remain as-is (unilingual alt attributes)
- All bilingual pages now contain an extra isBilingual indicator variable
- Splash page's isBilingual variable is currently unused
CC @bsouster @duboisp

Theme: Update wordmark code and add isBilingual var

---

site/pages/gcweb-theme/release/v8.0-en.hbs
site/pages/gcweb-theme/release/v8.0-fr.hbs

Added `<del>` in before and `<strong>` in after + added important notices + added visual impact for useful elements like alert boxes and an anchor to complete code.

Improve migration instructions for slim header

---

site/pages/gcweb-theme/release/v8.0-en.hbs
site/pages/gcweb-theme/release/v8.0-fr.hbs

I had issues with the language flip link being on the left of the Government of Canada logo when following the migration instructions for GCWeb v8.0. I found that the Canada.ca wb-lng has the pull-right class to help make the wb-lng stay to the right of the Government of Canada logo, while the instructions don't have this class.

Adding pull-right to language toggle instructions

---

src/plugins/chatwizard/chatwizard.js

The Reset and Minimize buttons rely on the title attribute for labels. I would propose including a more substantial label for the buttons. I made a change to update the buttons to be inline with what is done for the Overlay feature, an invisible span containing the text label.

Update chatwizard.js - Reset and Minimize button labels

---

src/plugins/actionmng/actionmng.js

This fixes the reported Excel issue with opening the downloaded csv

Add BOM to UTF-8 file

---

site/pages/provisional-en.hbs
site/pages/provisional-fr.hbs
src/plugins/gc-subway/_base.scss
src/plugins/gc-subway/_screen-md-min.scss
src/plugins/gc-subway/gc-subway-en.hbs
src/plugins/gc-subway/gc-subway-fr.hbs
src/plugins/gc-subway/gc-subway.js

**Changes include:**
- Prevent most of the on-load blinking with the addition of a "no-blink" shows the plugin after it is initialized, but the plugin does show in Basic HTML mode no matter what. Also, this only affects desktop mode;
- Add breakpoints to the resize event triggers, in order to make DOM shift smoother;
- Make sublists work and look right (also with .noline), plus add one to the working example;
- Clean inline-block on a float left element and some spacing.
Closes #1715

GC Subway - Multiple small fixes

---

package-lock.json
package.json
site/pages/index-en.hbs
site/pages/index-fr.hbs

This is a **MINOR release** (without breaking changes):
The following lists all the "What's new?" items since the last regular release (non-STR), which was v8.0.
* **template:**
* Patch - Follow - google plus removed from follow template
* Head - Remove no longer supported Internet Explorer conditionals
* **Styles and plugins:**
* Minor - JSON Manager - Make it usable without fetching a JSON file applied in each files
* Action Manager - Add BOM to UTF-8 file to fix character encoding on CSV export
* **[Provisional](https://wet-boew.github.io/themes-dist/GCWeb/provisional-en.html):**
* Fix - GC Subway - Fix "active" status on a sublist item that is currently viewed
* Chat wizard - Fix special characters in French invisible text
* GC Subway - Multiple small fixes (e.g.prevent blinking)
* …

8.1.0 release

---

src/components/_base.scss

Panel headings are smaller than actual content inside its body
Closes https://github.com/wet-boew/GCWeb/issues/1726

JIRA ticket WET-143 (Panel headings are smaller than actual content inside its body)

---

src/mobile-centre/_base.scss

Related to WET-115
Prevent the "X close" link to appear beside each individual block when a user navigate with the table multi-page navigation.
To reproduce: 
1. Go in the mobile center page,
2. Click on "Next" underneath the table (in the table navigation)
3. The "X Close" link appear beside each block.
Expected
* There is no "X Close" that appear on step 3

Mobile center - Prevent Close link to appear on table nav next

---

site/pages/index-en.hbs
site/pages/index-fr.hbs
site/pages/topic-testcase-1-en.hbs
site/pages/topic-testcase-1-fr.hbs

This alternative template avoid to have the "contributor" section to float in the middle of the page when there is not a lot of doormat link in the service and information section.
The fix is to remove the floating CSS class (pull-right, pull-left) and to move the "Most requested" section after the "Service and information" section. 
PP reference number: WET-155
@delisma can you ask if DTO are ok with that change for this special edge case?

Topic template - Test case 1 - Alternative template when right column is higher

---

site/pages/component/gc-table-en.hbs
site/pages/component/gc-table-fr.hbs
src/_provisional.scss
src/views/_screen-sm-max.scss

- Turns tables into cards items when on mobile (xxs and xs) view
- Optional responsive class to create cards on tablet (sm) view for tables that have extensive word content that should break into cards at this viewport too
- Optional class to make font size smaller for lengthy worded table content (just playing with it, may remove)

Feature: responsive table

---

src/social-media-icons/_base.scss

Previously, when a long social media channel name was placed into one of this component's list items, it'd split across multiple lines. But its line height would create an excessive amount of space between each line.
This addresses it by reducing the line height and by using another means of making single-line text look vertically-centered compared to the social media icons.
**Before:**
**After v1 (outdated - YouTube link's lines are noticeably closer together):**
**After v2 (YouTube link's lines are even closer together):**
CC @delisma @luc-bertrand-hrsdc @GormFrank

On social media (.gc-followus): Reduce line height

---

src/plugins/gc-subway/gc-subway.js

This PR replaces the semantics for the decorative H1 on desktop from a paragraph to a div. It also adds a skip link to the first H1 which is dedicated to the subway.
Blocked by https://github.com/wet-boew/wet-boew/pull/9036

GC Subway: Fix accessibility issues

---

sites/_defaults.scss
sites/_variables.scss
sites/gcweb-menu/_base.scss
sites/gcweb-menu/_screen-md-min.scss
templates/_search.scss
templates/search/api.html

---
name: Bold weight match
about: Update bold weight to match the font import
title: 'fix: Update _default.scss'
labels: ''
assignees: ''
---
This request fix an implementation issue with the bold weight. The bold weight was set to 600 but the font import only has 400 and 700 weight. Even if browsers tend to fallback to the 700 weight, we want to avoid unexpected behaviour and/or side effects.

fix: Update bold weight to 700

---

components/baseline/_base.scss
components/gc-follow-us/_base.scss
misc/views/_screen-sm-max.scss
sites/_defaults.scss
sites/_variables.scss

* Replaces GCWeb's heading font size variables (``$h#-size``) with overrides for Bootstrap's ones (``$font-size-h#``)
* Removes redundant SCSS selectors (Bootstrap already has them)
* Corrects estimated pixel size comment for the H1 heading's top margin in small view and under (from ~15px to ~26px)

Theme: Improve h1-h6 font size declarations

---

components/baseline/wet-boew-overrides.scss

Prevents closed captions that contain 2 lines of text from causing the CC container's height to shift during playback (due to GCWeb's taller line height).
The shifting can be distracting when the captions update (i.e. switching between no captions, 1 line captions and 2 line captions).
Depends on wet-boew/wet-boew#9082.
**Before** (CC container height: hardcoded 3em + 1em for padding):
**After** (CC container height: calculated 3.3em + 1em for padding):

Multimedia player: Increase CC container's height

---

_includes/alert-provisional.html
accueil.md
home.md

Very minor changes. This is just content related. No impact on the API.
1. We could see `{::nomarkdown}` render on GCWeb's home page.
2. There were some grammar errors in the provisional alert banner.

Doc: Remove visible markdown on home & fix grammar on provisional alert

---

components/gc-table/_screen-sm-max.scss

This component normally right-aligns data cells and floats their column labels to the left. That's fine for column labels that can fit on a single line. But ones that span across multiple lines end up becoming right-aligned - which looks really strange.
This resolves it by explicitly aligning column label text to the left.
**Before:**
**After:**

GC tables: Left-align column labels

---

components/gc-table/_screen-sm-max.scss

This component's table rows use bottom margins to space-them out when they're presented like mini-tables. But that margin doesn't serve any purpose on the last row. Especially since the table itself already has its own 23px bottom margin that doesn't collapse with the row margins.
Red is the last row's bottom margin, whereas yellow is the table's bottom margin.
**Before:**
**After:**

GC tables: Remove last row's bottom margin

---

components/gc-table/_screen-sm-max.scss
components/gc-table/gc-table-en.html
components/gc-table/gc-table-fr.html

A double-border effect used to appear in small view and under when pairing GC tables alongside Bootstrap's "table-bordered" class.
This resolves it by disabling that class' extra borders when GC tables' styles are in effect. Also adds an example of that class in use.
**Before:**
**After:**

GC tables: Support the "table-bordered" class

---

components/gc-table/_screen-sm-max.scss
components/gc-table/gc-table-en.html
components/gc-table/gc-table-fr.html

A bottom table border used to appear in small view and under when pairing GC tables alongside WET's tables (DataTables) plugin.
This removes that border when GC tables' styles are in effect. Also adds an DataTables example.
**Note:**
I also wanted to make GC tables disable datatables' optional scrolling features, but was unable to since its scrolling container is situated outside the table.
**Before:**
**After:**
**PS:**
This will need to be rebased after #1841 gets merged.

GC tables: Add partial DataTables support

---

components/gc-table/_screen-sm-max.scss
components/gc-table/gc-table-en.html
components/gc-table/gc-table-fr.html

Bootstrap's "tables" class adds a 2px border between adjacent ``tbody`` elements.
But it looked out of place in GC tables. That component adds a bottom margin to every row... which caused the adjacent ``tbody``'s top border to look like it was "sticking" to its first row.
This resolves it by adding a top margin to the adjacent ``tbody``'s first row to prevent the sticking. That allows the top border to look like a real separator. Also adds a second ``tbody`` to the first GC tables example.
Spinoff of #1843.
**Before:**
**After:**
CC @jmealing @delisma @duboisp

GC tables: Support adjacent tbodies

---

misc/views/_screen-sm-max.scss
sites/_defaults.scss

Related to: wet-141
The class `.gc-features` has been added to the existing Service and information component in order to apply the same CSS font-size ratio.

GC Initiatives - apply excat same font size as doormat link

---

.eslintrc.json

* Prevents ``let``/``const``/``Map``/etc from triggering errors
* Port of wet-boew/wet-boew#9166

ESLint: Set environment to ES6

---

_data/templates.json
templates/ministerial/index.json-ld
templates/ministerial/ministerial-doc-en.html
templates/ministerial/ministerial-doc-fr.html
templates/ministerial/ministerial-en.html
templates/ministerial/ministerial-fr.html

Minor updates to the Ministerial profile page template:
- Removal of the following sections: Latest, Recent activities, Twitter feed, Follow us and Gallery
- Creation of a Features optional section v6.1
- Change for 9 col instead of 6
- Creation of a documentation page (Eng and Fra)

wet-195 Ministerial-profile GCWeb template updates

---

index.md

Changes brought by #1888 were breaking current implementation of the GCWeb splash page.

Splash page: Update to #1888 (front matter)

---

components/gc-subway/docs-en.html
components/gc-subway/docs-fr.html

GC Subway: Add documentation about the two hyperlinks per item.
GC Subway working example has two hyperlinks for every bullet. Each hyperlink show up at different breakpoints, one is to offer an SPA feel when user is on mobile by having an anchor on an H1 and the other is the same link with no anchor, which is for regular surfing on a computer.
The goal of this PR is to document this choice of having two hyperlinks per item, and that it is optional. An item could have just one hyperlink without the anchor.

GC Subway: Add documentation about the two hyperlinks per item

---

sites/breadcrumbs/breadcrumbs-en.html
sites/breadcrumbs/breadcrumbs-fr.html
sites/breadcrumbs/inc-breadcrumbs.html

Previous breadcrumb used typeof=”Breadcrumb”, which doesn’t offer a data structure as rich as the typeof=”BreadcrumbList”.
This PR will replace it with the typeof=”BreadcrumbList” approach, which includes things such as a typeof ListItem on each list items.
Here is a valid example: https://search.google.com/test/rich-results/result?id=zGU8HNwVFWXt4fBPF2cl8w
As per WET-148

Adjust the structured data for breadcrumb

---

components/gc-features/gc-features-en.html
components/gc-features/gc-features-fr.html

This PR does quite a few things related to Features:
- Fixes the equal height classes in templates
- Clearly indicate .gc-initiatives as deprecated.
- Adjusted version numbers since there was never a version 9.4.2, we jumped straight to 9.5.0 because it was a minor;
- Plus, I adjusted some discrepancies.
Once Equal height CSS is investigated and fixed to work in the features context, we will update the template to accept both equal heights solution with a preference on the pure CSS version.
Also related to MWS-2096
@duboisp

Features: Fix equal height in template, adjust version number in documentation

---

_data/templates.json
docs/static-header-footer/site-assets/x-bootstrap-4.css
index-fr.md
sites/footers/_base.scss
sites/footers/footers-en.html
sites/footers/footers-fr.html
sites/footers/includes/footer.html
sites/footers/index.json-ld
sites/footers/no-footer-about-en.html
sites/footers/no-footer-about-fr.html
sites/footers/no-footer-site-en.html
sites/footers/no-footer-site-fr.html
sites/footers/no-footers-en.html
sites/footers/no-footers-fr.html
sites/inc-skiplinks.html
templates/index.json-ld

- A new variable 'noFooterSite' has been created in order to hide all utility links from 'About this site' section.
- The `noFooter` variable has been updated to `noFooterAbout` to be consistent with sections name.
- A working example for each footer options have been created
**Release note:**
When using `noFooterSite` to hide utility links from the footer, in order to keep the wordmark in place, the `col-lg-2` is removed and `col-md-3` is replaced by `col-md-12` from the `div` element

Footer options - Hiding utility links and create working examples

---

components/gc-subway/_base.scss
sites/helpers/_base.scss

Related to: 
PR# https://github.com/wet-boew/wet-boew/pull/9262
Removal of useless '!important' to certain class to ensure proper testing of WCAG 2.1 success criterion SC.1.4.12 Text Spacing.

WCAG Upgrade SC.1.4.12 - Removal of important from certain class

---

package.json

Avoids a "No repository field" warning when running ``npm install``.

Package: Add repository field

---

_config.yml

It was originally written in lower case... but GitHub Pages' URLs are case-sensitive.
This change also indirectly fixes a broken link in the Canada.ca FIP image in most of GCWeb's page templates. That link points to the ``setting-website`` variable's value, which is sourced from the ``website`` variable.

Site config: Use mixed-case "GCWeb" in website URL

---

components/wb-fieldflow/_base.scss
sites/baseline/_forms.scss
sites/theme.scss

Padding bottom was useless for inline fieldflow pattern.
This PR can be tested on the GCWeb page with WET-BOEW compiled demos: https://wet-boew.github.io/gcweb-compiled-demos/wetboew-demos/filter/filter-en.html
Plus, it can be tested on the index page and on Fieldflow main working example page (inline pattern). 
Furthermore, as an additional test you can add the following blurb of HTML in the inspector:
```
<div class="input-group">
<div class="input-group-addon">$</div>
<input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
<div class="input-group-addon">.00</div>
</div>
```
**In addition to this, I added css include recent fix for Equal height CSS component.**

Filter: Increase input height to match adjacent button

---

méli-mélo/méli-mélo-en.html
méli-mélo/méli-mélo-fr.html

Simplify and improve main méli-mélo documentation page for future contributors.
Live example for review here: https://gormfrank.github.io/website-gcweb/meli-melo.html (ignore broken links)

Méli-mélo: Major edits to documentation

---

components/wb-fieldflow/fieldflow.js

Prevents single/double quotes from causing fieldflow to truncate its form fields' value attributes.
Examples of scenarios this helps with:
* i18n.btn variable containing double-quotes (fieldflow names its submit button after it)
* List items containing single quotes (fieldflow uses them as checkbox/option/radio button values)
* Form action attributes containing URL parameters with single quotes in their values (fieldflow creates hidden inputs for them)
Fixes #1744.

Fieldflow: Escape quotes in value attributes

---

_data/sites.json
docs/static-header-footer/bootstrap-3.html
docs/static-header-footer/bootstrap-4.html
docs/static-header-footer/site-assets/x-bootstrap-4.css
sites/footers/deprecated/footers-v1-en.html
sites/footers/deprecated/footers-v1-fr.html
sites/footers/footers-en.html
sites/footers/footers-fr.html
sites/footers/index.json-ld
sites/footers/no-footer-site-en.html
sites/footers/no-footer-site-fr.html

GCWeb's footer contains two lists of links:
* The first list used to appear as a 1 column list in extra-small view and under.
* The second list used 1 column in extra-extra-small view and 2 columns in extra-small view.
That setup caused the footer to look unusually long and inconsistent on smartphones in landscape orientation.
This resolves it by adjusting the first list to use the ``colcount-xs-2`` class.
Related changes:
* Add deprecated footer pages to demonstrate the old pattern
* Add short explanations to distinguish the old and new patterns
**Screenshots:**
* **Extra-small view...**
* **Before:**
* **After:**
**Bonus screenshots (for reference):**
* **Extra-extra-small view (Before + After)...**
* **Small view (Before + After)...**

Theme: Use 2 columns for first footer list in xs view

---

templates/home/home-en.html
templates/home/home-fr.html

modify the home template to Remove Share this page button.
as per WET-237 request.

Remove Share this page button from Canada.ca home page

---

Gruntfile.coffee

By default, the "sass" task (via ``grunt-sass`` and ``node-sass``) generates CSS files using 2 space indentation. This change adjusts it use single tab indentation.
Advantages:
* Matches the indentation style of WET and GCWeb's source CSS/SCSS files
* Reduces the file size of generated unminified CSS files
Notes:
* Excludes méli-mélo CSS files:
* The "sass" task doesn't process them
* Their indentation styles are inconsistent (.editorconfig directs them to use tab indents, but some pre-existing files use spaces/mixed indents)
* Port of wet-boew/wet-boew#9375

Build: Use tab indentation for unminified CSS

---

sites/_variables.scss

* Necessary due to GCWeb using a wider font face than WET
* Prevents the asterisk from appearing on a separate line in Chromium/Firefox when a required standalone checkbox uses a multi-line label
* Fixes label/legend offsetting issues in Chromium/Firefox:
* The first line of required labels/legends was previously getting shifted rightwards, which made the first line look misaligned compared to nearby field controls and subsequent lines in multi-line labels/legends
* Increases space between asterisks and required labels/legends in IE11 due to CSS bugs involving pseudo-elements in that browser
* Follow-up to wet-boew/wet-boew#9371
**Screenshots:**
* **Firefox (Chromium is virtually identical)...**
* **Required text field with multi-line label:**
* **Before:**
* **After:**
* **Required …

Forms: Increase required asterisk variable's width

---

_data/templates.json

Running ``grunt`` on a clean ``master`` branch was polluting the working directory since the repo's version of ``_data/template.json`` was out of date (probably a leftover from #1993).
This commits the aforementioned changes.

Jekyll: Update templates data file

---

components/gc-servinfo/gc-srvinfo-examples.html
components/gc-subway/gc-subway-en.html
components/gc-subway/gc-subway-fr.html
components/gc-subway/index-en.html
components/gc-subway/index-fr.html
components/gc-subway/page2-en.html
components/gc-subway/page2-fr.html
components/wb-chtwzrd/chatwizard-en.html
components/wb-chtwzrd/chatwizard-fr.html
components/wb-chtwzrd/chatwizard-json-en.html
components/wb-chtwzrd/chatwizard-json-fr.html
components/wb-data-json/index.json-ld
components/wb-jsonmanager/index.json-ld
components/wb-urlmapping/ajax-en.html
components/wb-urlmapping/ajax-fr.html
components/wb-urlmapping/geomap-en.html
components/wb-urlmapping/geomap-fr.html
components/wb-urlmapping/patches-en.html
components/wb-urlmapping/patches-fr.html
components/wb-urlmapping/tblfilter-en.html
components/wb-urlmapping/tblfilter-fr.html
components/wb-urlmapping/urlmapping-doc-en.html
components/well-bold/well-bold-en.html
components/well-bold/well-bold-fr.html
index-fr.md

1. Addition of the following navigation buttons to component example pages:
* "Documentation" in order to navigate back to the documentation page from the component example page.
* "Questions or comments?" to navigate to a form on github where you can insert a comment, a question and/or raising an issue related to the component.
2. Fixing French language script on the index page for components example links to point to the French version. Currently, it falls back to the English version.
3. Fixing documentation inks that were still pointing to GCWeb when they were supposed to point to WET-BOEW

Components example - addition of navigation buttons

---

sites/includes/i18n.liquid
sites/page-details/includes/footer.html

"Page details" was previously hardcoded into the footer include's visually-hidden ``H2`` heading. As a result, French pages were using the English version of that heading.
This resolves it by adding an ``i18nText-pageDetails`` variable and using it in place of the English heading content.

Footer: Add a page details i18n variable

---

méli-mélo/2021-05-conjunction/and-or.css

Avoiding a "double line" look when stacked, making the "and" design borders the same as side-by-side (top/bottom rather than left/right)

keeping stacked "and" design same as side-by-side

---

components/gc-features/gc-features-en.html
components/gc-features/gc-features-fr.html

Changing GC Features component to use CSS equalheight feature instead of its JavaScript equivalent.
Related to WET-269

GC Features: JS equalheight to CSS equalheight

---

_data/méli-mélo.json

As requested by CRA and because it is still an active file for them, we are adding the 2021-05-steps in the current méli-mélo compilation. 
Note: Additional update are on its way for the steps experimentation.

Méli-mélo - add 2021-05-steps in 2023-10-mount-revelstoke compilation

---

_data/sites.json
sites/footers/deprecated/footers-v1-en.html
sites/footers/deprecated/footers-v1-fr.html
sites/footers/deprecated/footers-v2-en.html
sites/footers/deprecated/footers-v2-fr.html
sites/footers/footers-en.html
sites/footers/footers-fr.html
sites/footers/includes/footer.html
sites/footers/index.json-ld
sites/footers/no-footer-about-gov-en.html
sites/footers/no-footer-about-gov-fr.html
sites/footers/no-footer-support-links-en.html
sites/footers/no-footer-support-links-fr.html
sites/footers/no-footers-en.html
sites/footers/no-footers-fr.html
sites/footers/only-footer-about-gov-en.html
sites/footers/only-footer-about-gov-fr.html
sites/footers/only-footer-contextual-en.html
sites/footers/only-footer-contextual-fr.html
sites/footers/only-footer-site-en.html
sites/footers/only-footer-site-fr.html
sites/includes/i18n-core.liquid
sites/includes/i18n.liquid
sites/skiplinks/index.json-ld
sites/skiplinks/skiplinks-en.html
sites/skiplinks/skiplinks-fr.html

Changes included in this PR: 
- Editorial change - Update code sample for footer version 2 English - The code sample in the "version 2.0 (deprecated)" should match the version 2 of the working example.
- Editorial change - Update code sample for footer version 1 French - The code sample in the "version 1.0 (déprécié)" should match the version 1 of the working example.
- Editorial change - Change the parameter noFooterAbout for the "no-footer-about-en.html" to be replace by "no-footer-about-gov-en.html". (English and French) This to remove the confusion between the h2 heading (About this site) vs only the h3 heading (Government of Canada).
- Editorial change - Change the parameter noFooterSite in "no-footer-site-en.html" for something like "no-footer-support-links-en.html" (English and …

Footer: editorial changes

---

sites/footers/_base.scss

Removing the following flexbox utility classes:
- `.d-flex`
- `.align-items-center`
- `.align-self-end`
This PR is dependent on: https://github.com/wet-boew/wet-boew/pull/9461
Changes related to WET-289

Footer: removing flexbox utility classes

---

méli-mélo/2021-05-conjunction/and-or.css
méli-mélo/2021-05-conjunction/edge-cases.html
méli-mélo/2021-05-conjunction/index-fr.html
méli-mélo/2021-05-conjunction/index.html

Added option to remove border to always stacked patterns when already contained in a visible design constraint (e.g. panel or zebra striping) to minimize the design and remove the redundant double border.  Also removed margin-left: 5px from stacked design to allow custom use of margin.

Méli-mélo 2021-05-conjunction - Add support for no border

---

Gruntfile.coffee
docs/developing-en.md
docs/developing-fr.md

Running `grunt demo --branch=[branchName]` will generate dist files url's that work on the demo repository (https://github.com/ServiceCanada/wet-boew-demos/)
Also fixed some inconsistencies with new lines.
Changes related to WET-298

Grunt: Adding capability to generate demo files

---

_config.yml
_data/sites.json
sites/footers/custom-transparency-links-en.html
sites/footers/custom-transparency-links-fr.html
sites/footers/includes/footer.html
sites/footers/index.json-ld
sites/includes/i18n.liquid

Transparency links in sub-footer band can now be customized either globally or on a per-page basis. If the links are neither defined on the page or globally, they will default to the Canada.ca transparency URLs.

Footer: customizable transparency links

---

components/wb-actionmng/actionmng.js
components/wb-doaction/doaction-doc-en.html
components/wb-doaction/doaction-doc-fr.html
components/wb-doaction/tblfilter-en.html
components/wb-doaction/tblfilter-fr.html

Adding the ability to filter on whole table when the column property is not defined. If a column if not defined, the value will be added to the datatables search box (default datatables behaviour).
Changes related to WET-297

DoAction: Ability to search on the whole table

---

Gruntfile.coffee

Adding dependencyChecker task when running `grunt` (or `grunt debug`), `grunt dist` or `grunt méli-mélo`.  This should fix package update issues when rebasing or switching to a new branch.

Build: Adding dependencyChecker when running grunt

---

components/wb-fieldflow/alternative-en.html
components/wb-fieldflow/alternative-fr.html
components/wb-fieldflow/fieldflow.js

Providing a ``value`` in the ``query`` action causes fieldflow to set it as the ``select`` option's value when that action runs. But it previously wasn't working for empty values.
This fixes it by changing a couple of truthy ``if`` conditions into ``typeof`` string checks.

Fieldflow: Support empty values in query actions

---

Gruntfile.coffee
index-en.md
index-fr.md
sites/gcweb-menu/ajax/sitemenu-v5-en.hbs
sites/gcweb-menu/ajax/sitemenu-v5-fr.hbs
templates/institutional/institution-arms-en.html
templates/institutional/institution-arms-fr.html

Resolving build warnings part 2:
- Removing aria-hidden instruction for WET-BOEW demos on GCWeb (visible for form-valid and post-feedback)
- Converting hbs comment to HTML comment
- Removing reference to string which was unnecessary in institution-arms

Build warnings: WET demos alerts, syntax errors

---

templates/localnav/index-en.html
templates/localnav/index-fr.html
templates/organizational/organizational-arms-en.html
templates/organizational/organizational-arms-fr.html
templates/organizational/organizational-en.html
templates/organizational/organizational-fr.html
templates/service-en.html
templates/service-fr.html
templates/theme-en.html
templates/theme-fr.html
templates/topic/topic-en.html
templates/topic/topic-fr.html
templates/topic/topic-testcase-1-en.html
templates/topic/topic-testcase-1-fr.html

Resolving build warnings part 5:
- Fixing syntax for reference to page title

Build warnings: Fixing page title references

---

components/byline/includes/byline.html
components/components-en.html
components/components-fr.html
sites/gcweb-menu/ajax/sitemenu-en.hbs
sites/gcweb-menu/ajax/sitemenu-fr.hbs
templates/content-gcweb-4-0-29-font-style-en.html
templates/content-gcweb-4-0-29-font-style-fr.html
templates/institutional/institution-contact-en.html
templates/institutional/institution-contact-fr.html
templates/institutional/institutional-service-performance-en.html
templates/institutional/institutional-service-performance-fr.html
templates/theme-en.html
templates/theme-fr.html

Resolving build warnings part 4:
- Fixing byline file include which did not recognize "i18nText-lang"
- Fixing syntax for "byline" include call
- Fixing syntax and url for "placeholdercontent" include call
- Integrating "comp-download" include content directly in files calling it (2 files)
- Integrating "minister-port" include content directly in files calling it (2 files)
- Integrating "fullmenu" include content directly in files calling it (2 files)
- Integrating "carousel-small" include content directly in files calling it (2 files)

Build warnings: includes, byline and more

---

sites/header/header-docs-en.html
sites/header/header-docs-fr.html
sites/language/includes/languagetoggle.html
sites/language/index.json-ld
sites/language/language-en.html
sites/language/language-fr.html
templates/splash/api-en.html
templates/splash/api-fr.html
templates/splash/splashpage-contextual-en.md
templates/splash/splashpage-contextual-fr.md
templates/splash/splashpage-en.md
templates/splash/splashpage-fr.md

- Creation and addition of the documentation and working example for the Language Toggle link.
- Update the language toggle link and the language selection buttons from the splash page with the `translation="no"` attribute.

Avoid translation - Language toggle + Splash page language selection buttons

---

templates/institutional/institution-arms-en.html
templates/institutional/institution-arms-fr.html
templates/institutional/institution-en.html
templates/institutional/institution-fr.html
templates/localnav/index-en.html
templates/localnav/index-fr.html
templates/organizational/organizational-arms-en.html
templates/organizational/organizational-arms-fr.html
templates/organizational/organizational-en.html
templates/organizational/organizational-fr.html
templates/theme-en.html
templates/theme-fr.html
templates/topic/topic-en.html
templates/topic/topic-fr.html
templates/topic/topic-testcase-1-en.html
templates/topic/topic-testcase-1-fr.html

Several page templates had flawed H1 heading implementations. Probably mostly-caused by handlebars leftovers.
Specifically:
* Some templates showed duplicate H1s:
* Caused by using both a hardcoded H1 and a default Jekyll layout (which already comes with a built-in H1)
* Some templates showed one H1:
* Using a standard-looking hardcoded H1 (not in a grid) and the "without-h1" Jekyll layout... i.e. unnecessarily-complicated setup
This resolves it by:
* Removing hardcoded standard-looking H1s from pages that use the default Jekyll layout
* Adding the "without-h1" Jekyll layout to pages that use a hardcoded H1 in a grid
* Removing both hardcoded H1s and the "without-h1" layout from pages that don't actually need them
Note:
* Didn't update modified dates since these changes just restore …

Templates: Fix flawed H1 heading setups

---

_data/sites.json
sites/footers/contextual-example-en.md
sites/footers/contextual-example-fr.md
sites/footers/index.json-ld

Working example that show different type of URL used in the contextual footer.
FYI - @delisma

Footers - Contextual footer link variations

---

README.md

This fixes the "CGWeb" typo in the title of the French README,
and fixes the URL fragments in the hyperlink for jumping between English and Français (at least on GitHub).
Thanks!

Fix typo and English/Français URL fragment in README.md

---

components/gc-features/_base.scss

Re-applying the underline on hover of gc-features. New PR on WET applying box shadow to panels and wells containing a stretched-link.
Dependent on https://github.com/wet-boew/wet-boew/pull/9614 being merged.

gc-features: removing 'text-decoration: none' on hover

---

Gruntfile.coffee
sites/feedback/includes/feedback.html
sites/includes/settings.liquid

Page feedback global URL was adding `/GCWeb` since the URL was relative at some point. Since it is now absolute, there is no need for this logic.

Page feedback: fixing global GCWeb-Jekyll feedback url

---

components/gc-featured-link/_base.scss
components/gc-featured-link/gc-featured-link-en.html
components/gc-featured-link/gc-featured-link-fr.html
components/gc-featured-link/gc-featured-link.js

Adding option to customize the background colour of featured links.
Added CSS to hide the customized link by default to prevent a colour flick on load.

gc-featured-link: adding bg color option

---

common/button/button-en.html
common/button/button-fr.html
common/button/index.json-ld

This pull request includes a test page with working examples for the various button styles. More info can be found by referencing WET-361.

WCAG upgrade - Create test page for: Button

---

_data/common.json
_data/components.json
_data/templates.json
components/baseline/_base.scss
components/gc-stp-stp/_base.scss
components/gc-stp-stp/_screen-sm-min.scss
components/gc-stp-stp/gc-stp-stp-doc-en.html
components/gc-stp-stp/gc-stp-stp-doc-fr.html
components/gc-stp-stp/gc-stp-stp-en.html
components/gc-stp-stp/gc-stp-stp-fr.html
components/gc-stp-stp/includes/gc-stp-stp.html
components/gc-stp-stp/index.json-ld
sites/theme.scss
templates/advancedservice/index-fr.html
templates/advancedservice/page2-en.html
templates/advancedservice/page2-fr.html
templates/advancedservice/page3-en.html
templates/advancedservice/page4-en.html
templates/advancedservice/page4-fr.html
templates/advancedservice/page5-en.html
templates/advancedservice/page5-fr.html
templates/advancedservice/page6-en.html
templates/advancedservice/page6-fr.html

Adding .gc-stp-stp documentation and example.

Step by step navigation: adding documentation

---

components/gc-table/_screen-sm-max.scss
components/gc-table/gc-table-en.html
components/gc-table/gc-table-fr.html

Fixed display issue when table cell is empty. Previously looked like this (with overlapping):
Now looks like this with a new table row added for working example purposes:
The `flow-root` property allows for an element to preallocate its height as-if there was always a text value in it, and is supported by all major browsers. I tested Safari, Chrome and Firefox and everything looked good. No side effect on the existing examples.
I kept the GC Tables as a Provisional feature.

GC Tables: Improve display for empty cells

---

_data/sites.json
sites/feedback/index.json-ld

---
name: Update guidance links in feedback docs
about: This is a pull request to change the links to the feedback guidance in the design system.
title: 'docs: Update guidance links in feedback docs'
labels: 'documentation'
assignees: 'delisma'
---
Update guidance links for the feedback docs in sites.json and index.json-ld. From `https://design.canada.ca/continuous-improvement/monitoring/feedback.html` to `https://design.canada.ca/feedback/index.html` and `https://conception.canada.ca/amelioration-continue/mesure/retroaction.html` to `https://conception.canada.ca/retroaction/index.html`
n/a

docs: Update guidance links in feedback docs

---

sites/baseline/_font.scss

Fixing Lato font loading issue when cache is cleared or accessing site for the first time.
`font-display: fallback;` allows 3 seconds to load the font.

Fonts: fixing font loading

---

Gruntfile.coffee
_data/wet-boew.json
index-en.md
index-fr.md
wet-boew/bgimg/index.json-ld
wet-boew/favicon/index.json-ld

wet-boew folder created with two plugins inside as requested (as a start)
unable to run the "grunt" command

WET-410: Created a wet-boew section in GCWeb github

---

_data/sites.json
sites/feedback/index.json-ld
sites/feedback/page-feedback-contact-en.html
sites/feedback/page-feedback-contact-fr.html
sites/feedback/page-feedback-en.html
sites/feedback/page-feedback-fr.html
sites/layouts/documentation.html

- Removing soft launch alerts
- Moving iterations and changesets so that the newest ones are at the top
- Moving content of "semantic" to "include" property and adding correct info in "semantic" property
- Small fix in documentation layout so that the "breaking", "additions", and "fixes" are displayed

Feedback: removing soft launch alert, iteration and changeset edit

---

_data/sites.json
components/_base.scss
sites/archived/_archived.scss
sites/archived/archived-docs-en.html
sites/archived/archived-docs-fr.html
sites/archived/archived-overlay-en.html
sites/archived/archived-overlay-fr.html
sites/archived/index.json-ld
sites/headers-includes/archive.html
sites/layouts/documentation.html

Added new Archived variant without overlay and updated documentation to new data-first template.
Closes https://github.com/wet-boew/GCWeb/pull/2276

Archived: add new variant without overlay

---

méli-mélo/2021-05-steps/steps.css

Update to avoid cut off of lead zero in expand/hides in mobile and only allow margin top 0 for first child items in striped pattern.

Méli-mélo - 2021-05 Steps - Update css

---

_config.yml
_data/templates.json
sites/breadcrumbs/includes/breadcrumbs.html
sites/footers/includes/footer.html
sites/header/includes/header.html
sites/theme.scss
templates/application/_base.scss
templates/application/_print.scss
templates/application/_screen-xs-max.scss
templates/application/application-docs-en.html
templates/application/application-docs-fr.html
templates/application/application-with-banner-en.html
templates/application/application-with-banner-fr.html
templates/application/default-application-en.html
templates/application/default-application-fr.html
templates/application/index.json-ld
templates/application/layouts/application.html

Adding CDTS application elements inside an "Application" template.

Application: adding application template and examples

---

components/wb-fieldflow/alternative-en.html
components/wb-fieldflow/alternative-fr.html
components/wb-fieldflow/basic-en.html
components/wb-fieldflow/basic-fr.html
components/wb-fieldflow/fieldflow-en.html
components/wb-fieldflow/fieldflow-fr.html
components/wb-fieldflow/fieldflow.js

Previously, when the plugin encountered list items that didn't start off with an anchor, it used each item's first child node as a label/value. That was fine if the only child was a text node. But not when nested elements were in play...
For example:
* If a list item's first child node was an element node, ``wb.escapeAttribute()`` raised the following JS exception (since it expects strings - not element nodes):
* Uncaught TypeError: can't access property "replace", str is null
* If a list item started off with a text node and was followed by any element nodes, only the text node's content would be retained... resulting in the rest of the content getting truncated
This fixes it by deriving list item labels from their inner HTML code (like what's already done for anchors), as well as …

Field flow: Handle HTML tags in unlinked list items

---

common/alert/index.json-ld
common/alert/reports/a11y-1-en.html
common/alert/reports/a11y-1-fr.html
common/alert/reports/a11y-1.json

Related to reference number: wet-326

WCAG upgrade -- add WCAG assessment for alert component

---

sites/theme.scss

Imports WET's normalize.css overrides to obtain the fix.
Depends on wet-boew/wet-boew#9737.

Theme: Revert normalize.css' link outline styles

---

_data/sites.json
méli-mélo/2024-02-charts/demo.html
méli-mélo/2024-02-charts/index.html
méli-mélo/2024-02-charts/js/charts.js

Adding the following:
- Ability to display the table by default using the attribute "data-chart-details-open".
- Wrapping the <canvas> element in a container to allow for custom styling.
- Adding a <div class="table-responsive"> around the table to fix overflow issue on mobile.

Méli-mélo Charts: mobile table, canvas container

---

components/wb-fieldflow/fieldflow.js

Leading/Trailing spaces are usually undesirable, so let's strip them out.
Doesn't affect labels that are explicitly-declared via the "wb-fieldflow-label" class. Those will be kept as-is so as not to interfere with an implementer's desire.
Affects grouping and nesting scenarios. Directly impacts the demo page's nesting example.
Spinoff of #2291.

Field flow: Trim auto-generated labels/values

---

components/wb-fieldflow/fieldflow-en.html
components/wb-fieldflow/fieldflow-fr.html
components/wb-fieldflow/fieldflow.js

Removes HTML tags and escapes quotes from ``optgroup`` ``label`` attributes.
Also adds a ``strong`` element to the grouping example to demonstrate it in action.
Overlooked leftover from #2291.

Field flow: Cleanup optgroup labels

---

components/wb-fieldflow/fieldflow-en.html
components/wb-fieldflow/fieldflow-fr.html
components/wb-fieldflow/fieldflow.js

Anchors were previously detected by evaluating ``firstChild``'s node name... which only worked if the very first node was an anchor element.
As a result, if the first node was something other than an element (e.g. comment or text node with empty space)... they'd be evaluated instead of the real anchor and consequently mess up the redirection action.
This resolves it by evaluating ``firstElementChild`` instead of ``firstChild``. Also adds a comment and empty space to some of the redirection examples.

Field flow: Detect anchors via firstElementChild

---

_data/templates.json
sites/layouts/documentation.html
templates/institutional-landing/deprecated/institution-en.html
templates/institutional-landing/deprecated/institution-fr.html
templates/institutional-landing/deprecated/institution-landing-en.html
templates/institutional-landing/deprecated/institution-landing-fr.html
templates/institutional-landing/index.json-ld
templates/institutional/index.json-ld

Adding instructions for AEM users on how to implement the page template.
Dependent on https://github.com/wet-boew/wet-boew/pull/9758 being merged

Institutional landing page: adding AEM instructions

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Because 'Share this page' plugin was updated in wet-boew to add support for X social media.
Diff: https://gist.github.com/duboisp/d69787b300eb1f4d40f937508e10d013/revisions
Related to wet-boew PR # 9734
This need to be merged immediately before or after when we will update to the wet-boew version 4.0.80

CID - Update for the copy missing _sprite_share.scss

---

sites/gcweb-menu/ajax/sitemenu-v5-en.hbs
sites/gcweb-menu/ajax/sitemenu-v5-fr.hbs

The menu does not use the new tc.canada.ca domain and might stop working in the future.

Updating TC links to https://tc.canada.ca/ instead of https://www.tc.gc.ca/

---

sites/gcweb-menu/gcweb-menu-docs-en.html
sites/gcweb-menu/gcweb-menu-docs-fr.html
sites/gcweb-menu/menu.js

Updated aria-label of the GC-menu to make it accessible according to WCAG standards. This PR is linked to JIRA ticket WET-265.

GC-menu: Labelled for accessibility

---

common/button/button-fr.html
components/gc-minister/gc-minister-fr.html
components/gc-minister/gc-minister-special-cases-fr.html
components/gc-minister/gc-minister-two-ministers-fr.html
components/gc-most-requested/gc-most-requested-fr.html

Some French component pages were using English "Code sample" headings/summaries written without language switches. The rest of their content was fully written in French.
This revises the headings/summaries in question to "Exemple de code".

Components: Add French "Code sample" translations

---

sites/layouts/documentation.html
sites/layouts/documentation_pattern.html

The French versions of certain documentation pages contain named entities for non-breaking spaces (``&nbsp;``)... which were previously being rendered as separate characters instead of being interpreted.
This resolves it by setting the Data JSON plugin's ``isHTML`` option to ``true`` for all ``description`` variables. Mostly impacts ``summary`` and ``figcaption`` elements.

Docs: Render HTML in JSON description variables

---

_data/sites.json
sites/date-modified/date-modified-en.html
sites/date-modified/date-modified-fr.html
sites/date-modified/index.json-ld

That iteration's code samples had the following issues:
* Opening tags were coded as named entities (but not closing tags)... resulting in the named entities being literally shown in the samples
* French code sample wasn't categorized properly:
* Language was set to English
* Description was called "Code sample with contact link" (probably copied from one of the Page Feedback Tool [PFT]'s samples)
This resolves it by re-adding real opening tags and correcting French categorizations.

Date modified: Fix iteration 1's code samples

---

_data/components.json
components/gc-follow-us/_base.scss
components/gc-follow-us/gc-follow-us-en.html
components/gc-follow-us/gc-follow-us-fr.html
components/gc-follow-us/includes/gc-follow-us.html
components/gc-follow-us/index.json-ld

Social Media Channels - More ways to connect

---

méli-mélo/2024-04-stepsquiz/index-fr.html
méli-mélo/2024-04-stepsquiz/index.html
méli-mélo/2024-04-stepsquiz/js/stepsquiz.js
méli-mélo/2024-04-stepsquiz/meta.md
méli-mélo/2024-04-stepsquiz/reports/a11y-1-en.html
méli-mélo/2024-04-stepsquiz/stepsquiz-limited-en.html
méli-mélo/2024-04-stepsquiz/stepsquiz-limited-fr.html
méli-mélo/2024-04-stepsquiz/stepsquiz.css

Description:
- Fix minor content issue on language toggle.
- Further to an accessibility assessment, in order to meet WCAG criterias 1.3.1, 3.3.2 and 4.1.2, the form element `<progess>` must be accompanied or wrapped by a `<label>` element : [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#accessibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#accessibility).

Steps quiz - fix content and accessibility issue

---

Dockerfile
Gemfile

These Dockerfile updates resolve the issues encountered when running GCWeb with the latest Docker Desktop for Windows version 4.30.1. 
The updates have also been tested successfully on Docker Desktop versions 4.30.0,  4.19.0 and 4.10.1.

update ruby to v.3.3.0, install webrick

---

méli-mélo/2021-05-conjunction/and-or.css
méli-mélo/2021-05-conjunction/index.html
méli-mélo/2021-05-conjunction/meta.md
méli-mélo/2021-05-steps/meta.md
méli-mélo/2021-05-steps/steps.css

Added new exception to remove line separator  for side by side designs in high contrast mode for firefox as cannot resolve gradient pattern issue (going through text)

update CSS for high contrast

---

_data/sites.json
sites/main-page-title/index.json-ld

The visual update 2024 iteration's breaking change previously wasn't appearing.
It seems to have been related to structure issues in the JSON-LD file's "breaking" object:
* Array using curly brackets ( ``{...}`` )
* Key/value pair placed in the array (key was named "style")
This fixes it by:
* Using square brackets ( ``[...]`` ) for the array
* Replacing the "style" key with a "Style: " prefix in the value

Main page title: Show breaking change in VU 2024 iteration

---

.github/workflows/cd.yml
.github/workflows/ci.yml
Gruntfile.coffee
_data/wet-boew.json
package-lock.json
package.json

Update node for compatibility with lts versions 18 and 20.

Node update for compatibility with lts versions 18 and 20

---

_data/sites.json
méli-mélo/th-empathy/style.css
sites/main-page-title/_base.scss
sites/main-page-title/index.json-ld
sites/main-page-title/main-page-title-en.md
sites/main-page-title/main-page-title-fr.md

Some older browsers (most notably Safari <= 15.3) incorrectly set ``border-style: solid;`` whenever the ``border-image`` property was used. That in turn caused affected browsers to render the thickline style as a three-sided border.
This works around the issue by setting the thickline style's left/right/top ``border-*-width`` properties to 0.
Thanks to @donmcdill for pitching this approach (other ways I prototyped didn't work).
Fixes #2396.

H1 thickline: Fix border rendering bug in older browsers

---

components/wb-fieldflow/fieldflow-en.html
components/wb-fieldflow/fieldflow-fr.html
components/wb-fieldflow/fieldflow.js

When field flow's redirect (``redir``) action is used, submitting causes the plugin to "transform" the currently-selected dropdown ``option``'s URL parameters into hidden ``input`` elements. The ``input``s are created by passing "raw" HTML strings to the jQuery object.
That setup used to play nicely with URL parameters whose keys corresponded to the names of HTML attributes (e.g. ``lang=anything``). But it stopped working when wet-boew/wet-boew#9210 introduced DOMPurify into WET's jQuery 2.x implementation. Why? Because DOMPurify's ``sanitize()`` method filters-out ``name="[any HTML attribute name]"`` to prevent potential DOM clobbering attacks (see cure53/DOMPurify#980). End result is that jQuery ultimately returns ``name``-less ``input``s to the plugin, which in turn causes affected …

Field flow: Keep URL params matching HTML attributes

---

méli-mélo/2023-10-clipboard/js/clipboard.js

#2411 accidentally-introduced tab indents into the plugin's JS file.
It was caused by a clash of EditorConfig settings (which apply GCWeb's basic linting settings to all méli-mélo files) vs ESLint (which excludes méli-mélo). The added indents adhered to the EditorConfig settings, but the file itself was using a different kind of indent style (groups of 4 spaces).
This changes the tab characters back into spaces.

Clipboard plugin (méli-mélo): Restore space indents

---

_data/sites.json
sites/main-page-title/_base.scss
sites/main-page-title/index.json-ld
sites/main-page-title/main-page-title-align-right-en.md
sites/main-page-title/main-page-title-align-right-fr.md
sites/main-page-title/main-page-title-div-align-right-en.md
sites/main-page-title/main-page-title-div-align-right-fr.md
sites/main-page-title/main-page-title-div-stacked-align-right-en.md
sites/main-page-title/main-page-title-div-stacked-align-right-fr.md
sites/main-page-title/main-page-title-stacked-align-right-en.md
sites/main-page-title/main-page-title-stacked-align-right-fr.md

If the main title is aligned to right (dir="rtl") the bottom red underline will follow the same alignement.

Main page title: Short bord red underline - follow the title alignement

---

Gruntfile.coffee
package-lock.json
package.json

Minimum changes needed to get it to successfully build.
Contains countless deprecation warnings, but those can be dealt with in the future.
GCWeb port of wet-boew/wet-boew#9840.

Build: Replace Node Sass with Dart Sass

---

sites/baseline/_scaffolding.scss

#2450 added a CSS selector that set the ``word-break`` property to ``break-word`` anywhere within the ``main`` element.
But it had unexpected side effects in certain kinds of two-dimensional content, such as tables and input groups.
Specifically:
* It could cause wide tables (even ones situated within ``table-responsive`` containers) to divide their columns improperly - resulting in individual numbers in number groupings "splitting" across lines, columns that are too narrow to fit short words on the same line, non-breaking spaces getting ignored, etc...
* Buttons situated in input groups became "squished" - every letter within affected buttons appeared on its own line
This resolves it by reworking the selector to solely target paragraphs and headings. Paragraphs in table cells are …

Theme: Break words in paragraphs and headings only

---

templates/news/deprecated/news_v3-en.html
templates/news/deprecated/news_v3-fr.html
templates/news/news-doc-en.html
templates/news/news-doc-fr.html
templates/news/news-en.html
templates/news/news-fr.html

- Updating paragraphs above and below the news table.
- Adding instructions on what to do in basic HTML mode.
(wet-496)

News: updating news template

---

_data/components.json
_data/i18n.yml
_data/sites.json
_data/templates.json
components/_base.scss
components/byline/_base.scss
components/byline/byline-doc-en.html
components/byline/byline-doc-fr.html
components/byline/includes/byline.html
components/byline/index.json-ld
index-en.md
index-fr.md
sites/main-page-title/_base.scss
sites/main-page-title/includes/main-page-title.html
sites/main-page-title/index.json-ld
sites/main-page-title/main-page-title-byline-en.html
sites/main-page-title/main-page-title-byline-fr.html
sites/theme.scss

- Adding byline documentation so that it can be deprecated
- Adding "Main page title with byline" variation to the Main page title (this variation is limited to news pages on Canada.ca)
Related to WET-494

Byline: adding documentation, moving to main title

---

sites/resources-inc/footer.html

This PR is related to [GCWeb Jekyll](https://github.com/wet-boew/gcweb-jekyll) options and does not affect the distribution files, and it does not require a release to take effect. as the CD updates GCWeb Jekyll upon merging.
It allows for importing on a page scripts of various types, such as `module`.
This will enable running test pages with the GCWeb Jekyll theme for [GC Search UI](https://github.com/ServiceCanada/search-ui).
I have added working examples throug a [PR in the GCWeb Jekyll website sample](https://github.com/wet-boew/gcweb-jekyll-website/pull/1). When merged, example of success is that this page shows "Hello world from module" in the grey well: https://wet-boew.github.io/gcweb-jekyll-website/advanced/add-script-module.html
Related to **SR-454**

GCWeb Jekyll - Ability to import script of type module w/ front-matter

---

package-lock.json
package.json
sites/page-details/_base.scss

Caused by https://github.com/wet-boew/wet-boew/pull/9881

Page details: Bump WET-BOEW to 4.0.86.1 and fix typo indentation variable

---

Gruntfile.coffee
docs/developing-en.md
docs/developing-fr.md
package-lock.json
package.json

Remove the `grunt-bootlint` config. This was/is a useful tool for Bootstrap 3, but development has stopped by that team and the repos have been archived. Maybe it's still catching things and should be kept though.

build: remove grunt-bootlint

---

_config.yml
_data/common.json
_data/components.json
_data/templates.json
sites/resources-inc/head.html

In `_config.yml`, Set: `gcds: true` in the `global` property to activate GCDS globally. 
Optionally, set `gcds: [version number]` to define a specific version of GCDS. For example: `gcds: "0.33.0"`.
Finally, you can set `gcds: false` to deactivate GCDS, or simply remove the property.

GCWeb Jekyll: adding possibility to include GCDS in global proprties

---

_data/common.json
_data/components.json
_data/templates.json
_includes/web-contents/placeholdercontent-en.html
_includes/web-contents/placeholdercontent-fr.html
common/scaffolding/grouping-en.html
common/scaffolding/grouping-fr.html
common/scaffolding/index.json-ld

Will close the following duplicates
* close #2129 
* close #2131

Scaffolding: Adding examples for grouping elements

---

_data/components.json
_includes/components/gc-most-requested/gc-most-requested.html
components/gc-most-requested/_base.scss
components/gc-most-requested/_screen-md-min.scss
components/gc-most-requested/gc-most-requested-bad-en.html
components/gc-most-requested/gc-most-requested-bad-fr.html
components/gc-most-requested/gc-most-requested-doc-en.html
components/gc-most-requested/gc-most-requested-doc-fr.html
components/gc-most-requested/gc-most-requested-en.html
components/gc-most-requested/gc-most-requested-fr.html
components/gc-most-requested/gc-most-requested-provisional-en.html
components/gc-most-requested/index.json-ld
components/gc-most-requested/samples/gc-most-requested.html

This PR changes the distribution of Most requested items from top to bottom and from left to right instead of from left to right and top to bottom.
Before:
1 2
3 4
5 6
After:
1 4
2 5
3 6
Changes related to WET-488

Most requested: display items in columns

---

docs/méta-détails/th-vitality-en.html
docs/méta-détails/th-vitality-fr.html

Added the necessary documentation to fix broken vitality thematic link on the [GC promotional thematic page](https://wet-boew.github.io/GCWeb/th%C3%A9matique/gc-th%C3%A9matique-en.html).

Fixed broken vitality details link

---

.github/workflows/gh-pages.yml
docs/developing-en.md
docs/developing-fr.md

Feel free to close this, I was just seeing if I could get the GitHub Actions to work for deployment.
The path probably still isn't right for to scope down the pages.
You can see what it looked like when I pushed this against my own default branch before rolling back and changing the branch back to `dev` https://github.com/nschonni/GCWeb/actions/runs/14767194643

build: Use GitHub's Actions for Page deployment

---

sites/gcweb-menu/_screen-md-min-to-screen-md-max.scss
sites/gcweb-menu/gcweb-menu-docs-en.html
sites/gcweb-menu/gcweb-menu-docs-fr.html

Adjust the width of the 2nd level menu on medium breakpoints to avoid horizontal scroll on medium breakpoints

fix horizontal scroll on medium screen

---

_data/templates.json
sites/layouts/documentation.html
sites/theme.scss
templates/theme/_base.scss
templates/theme/_screen-lg-min.scss
templates/theme/_screen-md-min.scss
templates/theme/_screen-sm-max.scss
templates/theme/index.json-ld
templates/theme/sign-in-en.html
templates/theme/sign-in-fr.html
templates/theme/theme-doc-en.html
templates/theme/theme-doc-fr.html
templates/theme/theme-en.html
templates/theme/theme-fr.html
templates/theme/theme-youth-en.html
templates/theme/theme-youth-fr.html
templates/theme/theme.js

Dependent on PR #2410 being merged.
Changes related to: WET-467

Theme: adding theme template

---

_data/common.json
_data/components.json
_data/templates.json
components/gc-subway/gc-subway.js

Duplicating links in index page just like in sections page so that in mobile view they anchor to the content.

GC-Subway: adding mobile-specific links to index page

---

_data/méli-mélo.json
docs/méta-détails/2025-06-math-grid-en.html
docs/méta-détails/2025-06-math-grid-fr.html

This PR is for:
- add the `2025-06-math-grid`` experimentation to the mille-iles compilation in méli-mélo.json.
- create the according files of `2025-06-math-grid`` in docs/méta-détails

Add 2025-06-math-grid to the mile-iles compilation 

---

Gruntfile.coffee
_data/components.json
components/gcds-card/_workaround.scss
components/gcds-card/card-doc-en.html
components/gcds-card/card-doc-fr.html
components/gcds-card/card-en.html
components/gcds-card/card-fr.html
components/gcds-card/index.json-ld
components/gcds-card/mws-en.html
components/gcds-card/mws-fr.html
components/gcds-card/mws-no-workaround-en.html
components/gcds-card/mws-no-workaround-fr.html
components/gcds-card/withimg-en.html
components/gcds-card/withimg-fr.html
package.json
sites/gcdsloader.js
sites/resources-inc/head.html
sites/theme.scss

This introduce the initial addition of the GCDS libraries which will co-exist along with GCWeb.
GCWeb are going to be updated with more example as our co-existence component testing are going to progress.
Changes:
* Add GCDS-card working example
* Add a GCDS loader in our distribution package that are loading the tested compatible version of GCDS
* Include a workaround for a know issue with GCDS in the managed web services.

Add GCDS loader and GCDS card example for co-existance tested version

---

sites/theme.scss

Bootstrap's ``visible/hidden-*`` classes were previously unable to override WET's ``d-flex`` class due to the following:
* In GCWeb's compiled CSS file, Bootstrap's responsive utilities stylesheet (where the ``visible/hidden-*`` classes are declared) was imported before WET's main Bootstrap 4 stylesheet (where ``d-flex`` is declared).
* Both the ``visible/hidden-*`` and ``d-flex`` classes use ``!important`` flags in their ``display`` properties.
* Notes:
* WET's similar ``d-sm-flex`` class doesn't use ``!important``.
* Bootstrap 4.0's own ``d-flex`` class uses ``!important``.
* The ``visible/hidden-*`` classes' selectors didn't benefit from the fact that they all use media queries (media queries don't increase selector specificity).
This resolves it by importing Bootstrap's responsive …

Theme (SCSS): Reposition Bootstrap's responsive utilities
